=== 13.4.6 Working With Non-Substance Inventory Items

This section provides examples of INV segments related to reporting and querying values of equipment state indicators (special non-material inventory items).

*Example 1: Reporting that all tests are available (in INU^U05):*

INV|NONE^^HL70451|OK^^HL70383|||||||||||||||||||TA^^HL70942

*Example 2: Reporting that tests with LOINC codes 1492-8 and 1496-8 are available (in INU^U05):*

INV|NONE^^HL70451|OK^^HL70383|||||||||||||1492-8^^LN~1496-8^^LN||||||TA^^HL70942

*Example 3: Reporting that the current instrument processing capacity is 42 % (in INU^U05):*

INV|NONE^^HL70451|OK^^HL70383|||||||||||||||||||IC^^HL70942|42^%&&UCUM

*Example 4: Reporting that an output specimen buffer “Buffer1” is full (in INU^U05):*

INV|BufferId1^^HL70451|OK^^HL70383|||||||||||||||||||OB^^HL70942|100^%&&UCUM

*Example 5: Reporting that an emergency input specimen buffer “Buffer2” is empty (in INU^U05):*

INV|BufferId2^^HL70451|OK^^HL70383|||||||||||||||||||EB^^HL70942|0^%&&UCUM

*Example 6: Querying the current instrument processing capacity (in INR^U14):*

INV|||||||||||||||||||||IC^^HL70942

*Example 7: Querying the current capacity of all regular specimen input buffers (in INR^U14):*

INV|||||||||||||||||||||IB^^HL70942

*Example 8: Querying the current capacity of the regular specimen input buffer “Buffer3” (in INR^U14):*

INV|Buffer3^^HL70451||||||||||||||||||||IB^^HL70942

