=== 2.13.11 OVR – Override segment

Definition: This segment allows a sender to override specific receiving application's business rules to allow for processing of a message that would normally be rejected or ignored.

In many instances, business rules will be set as guidelines relative to patient care. In some instances it is in the patient's better interest to circumvent these guidelines. In other cases, business rules might exist to support normal process flow, but which couldbe bypassed or ignored under certain special circumstances. This segment is linked to the proposed ERR segment changes in that the first attempt to process a transaction that violates a business rule could result in an error that must be overridden. The ERR provides a mechanism to identify errors that MAY be overridden, as well as the allowed override codes.

Use case #1: A patient has received a prescription with a duration of 30 days and receives the full amount at their pharmacy. While at home the patient accidentally spills the container and spoils a significant proportion of the prescription. The patient returns to their pharmacy and explains the situation to the pharmacy technician. The technician consults with their supervising pharmacist. Knowing the patient, the pharmacist decides to override the business rule stating that the dispensed amount for a prescription can not exceed the prescribed amount. In recording the decision, the pharmacy technician specifies that the *Override Type* is a "Compassionate Refill" and that the *Override Code*, or reason for the override, is "Spoilage". The technician also provides *Override Comments* to provide an explanation of the situation for future reference. While recording the decision, the technician's user ID is automatically stored in an *Override Recorded By* field. The pharmacist's ID is stored in the *Override Responsible Provider* field.

Use case #2:A hospital wishes to submit an invoice to an insurer who is providing secondary coverage. The invoice is being submitted over a week after the service was performed, which is outside the insurer's normal accept time window. The insurer would normally reject the invoice. However, the submitter includes an *Override Type* of "late submission" as well as an *Override Code* indicating that the invoice is late due to delays with the primary payor. The secondary insurer examines the override reason and accepts the invoice.

Usage Note: The override segment SHOULD be included in messages adjacent to the segment(s) containing the information that would trigger the business rule(s) that needs to be overridden. The segment SHOULD be optional (you shouldn't always need to override business rules), and SHOULD be allowed to repeat in circumstances where there can be more than one business rule overridden at the same time. Committees MAY wish to provide suggested values for override types or codes for use with the OVR segment in different messages.

The following is an example of how the OVR segment might be used in a dispense message (RDS_O13):

MSH PID PV1 \{ORC RXE \{RXR} RXD \{RXR} <RXC> <NTE> <FT1> <OVR>}

HL7 Attribute Table – OVR – Override Segment

[width="100%",cols="14%,6%,7%,6%,6%,6%,7%,7%,41%",options="header",]
|===
|SEQ |LEN |C.LEN |DT |OPT |RP/# |TBL# |ITEM# |ELEMENT NAME
|1 | | |CWE |O | |file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70518[0518] |01829 |Business Rule Override Type
|2 | | |CWE |O | |file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70521[0521] |01830 |Business Rule Override Code
|3 | |200# |TX |O | | |01831 |Override Comments
|4 | | |XCN |O | | |01832 |Override Entered By
|5 | | |XCN |O | | |01833 |Override Authorized By
|===

