=== 2.13.12 SFT – Software segment

Definition: This segment provides additional information about the software product(s) used as a Sending Application. The primary purpose of this segment is for diagnostic use. There MAY be additional uses per site-specific agreements.

Implementers are encouraged to use message profile identifiers (as found in _2.13.9.21_, "_MSH-21 Message Profile Identifier (EI) 01598_") to control the behavior of the receiving application rather than relying on application or version information in the SFT segment.

For example, if software product A has versions 9 and 10 deployed in different Enterprise locations, the fact that they use different message types, segments, or fields SHOULD be reflected via their message profiles (see section 2B, "Conformance Using Message Profiles"). If there is an upgrade from version 10 to 10.1, this would be reflected in the SFT segment, but changes to the message contents SHOULD be reflected via a new/different conformance profile.

Use Case: An external application has been customized to communicate with a centralized patient drug history system. However, due to certain, known characteristics of the external software package, the centralized system must modify its behavior in order to process transactions correctly. In one example, the external application could have multiple versions in production. As such, the centralized application will need to know the name of the *Software Vendor Organization*, the *Software Release Number*, the *Software Product Name*, and the *Software Binary ID* so that it can correctly identify the software submitting the transaction and modify its behavior appropriately.

While preparing a transaction for submission to a centralized system the sending application specifies its *Software Install Date* and its configuration settings (*Software Product Information*). While processing the transaction, the centralized system encounters an error. Upon examination of the error, install date and configuration of the software that sent the message, helpdesk staff are able to determine the sending application has not been updated to reflect recent application changes.

Use Case: In circumstances where a message is manipulated or modified by multiple systems, a repetition of this segment MAY be appended by each system.

Example:

MSH

{empty}[\{ SFT }]

...

HL7 Attribute Table – SFT – Software Segment

[width="100%",cols="14%,6%,7%,6%,6%,6%,7%,7%,41%",options="header",]
|===
|SEQ |LEN |C.LEN |DT |OPT |RP/# |TBL# |ITEM# |ELEMENT NAME
|1 | | |XON |R | | |01834 |Software Vendor Organization
|2 | |15# |ST |R | | |01835 |Software Certified Version or Release Number
|3 | |20# |ST |R | | |01836 |Software Product Name
|4 | |20# |ST |R | | |01837 |Software Binary ID
|5 | | |TX |O | | |01838 |Software Product Information
|6 | | |DTM |O | | |01839 |Software Install Date
|===

