=== 2.13.10 NTE ‑ Notes and Comments segment

The NTE segment is defined here for inclusion in messages defined in other chapters. It is commonly used for sending notes and comments.

The work groups define the meaning of the NTE segments within the context of the messages in their chapters. For each NTE, the description in the message attribute table SHOULD include an indication of the segment associated with the NTE, for example "Notes and Comments for the PID".

NOTE: While sending of segments with no content has been historically used for display messages to indicate blank lines this is not best practice. Senders SHOULD NOT send empty NTEs to indicate blank lines. When blank lines are required senders SHOULD use the functionality of the FT datatype in section link:#formatting-codes[Formatting codes].

HL7 Attribute Table - NTE - Notes and Comments

[width="100%",cols="14%,6%,7%,6%,6%,6%,7%,7%,41%",options="header",]
|===
|SEQ |LEN |C.LEN |DT |OPT |RP/# |TBL# |ITEM # |ELEMENT NAME
|1 | | |SI |O | | |00096 |Set ID - NTE
|2 |1..1 | |ID |O | |file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70105[0105] |00097 |Source of Comment
|3 | | |FT |C |Y | |00098 |Comment
|4 | | |CWE |O | |file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70364[0364] |01318 |Comment Type
|5 | | |XCN |O | | |00224 |Entered By
|6 | | |DTM |O | | |00661 |Entered Date/Time
|7 | | |DTM |O | | |01004 |Effective Start Date
|8 | | |DTM |O | | |02185 |Expiration Date
|9 | | |CWE |O |Y |file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70611[0611] |03495 |Coded Comment
|===

