===== 2.9.4.1.1 Snapshot Mode and Repeating Segments - Example

Example A: if a patient record indicated a 2 sisters and a brother as next of kin, this would be represented as follows in the add person/patient information message:

MSH||||||||ADT^A28^ADT_A05|...<cr>

EVN|...<cr>

PID|...<cr>

NK1|1|Nuclear^Nancy^D|SIS^Sister^HL70063|...<cr>

NK1|2|Nuclear^Nelda^W|SIS^Sister^HL70063|...<cr>

NK1|3|Nuclear^Neville^S|BRO^Brother^HL70063|...<cr>

PV1|...<cr>

If, subsequently, the one of the sisters was delisted as next of kin, it would be necessary to send both the remaining "brother" and "sister" records in order to form a complete replacement set in an update person information message:

MSH|||||||||ADT^A31^ADT_A05|...<cr>

EVN|...<cr>

PID|...<cr>

NK1|1|Nuclear^Nancy^D|SIS^Sister^HL70063|...<cr>

NK1|2|Nuclear^Neville^S|BRO^Brother^HL70063|...<cr>

PV1|...<cr>

If all next of kin were to be subsequently delisted, an update message with a single delete indicator populated segment would instruct the receiving system to delete information represented by any prior set:

MSH||||||||ADT^A31^ADT_A05|...<cr>

EVN|...

PID|...

NK1|""|""|""|""|<cr>

PV1|...<cr>

Alternatively, as of v2.6, the deletion could be signaled by sending a delete indicatorin the first field of the NK1 segment. This is its only required field.

MSH||||||||ADT^A31^ADT_A05|...<cr>

EVN|...

PID|...

NK1|""|<cr>

PV1|...<cr>

