==== 10.6.8.3 APR-3 Location Selection Criteria (SCV) 00910

Components: <Parameter Class (CWE)> ^ <Parameter Value (ST)>

Subcomponents for Parameter Class (CWE): <Identifier (ST)> & <Text (ST)> & <Name of Coding System (ID)> & <Alternate Identifier (ST)> & <Alternate Text (ST)> & <Name of Alternate Coding System (ID)> & <Coding System Version ID (ST)> & <Alternate Coding System Version ID (ST)> & <Original Text (ST)> & <Second Alternate Identifier (ST)> & <Second Alternate Text (ST)> & <Name of Second Alternate Coding System (ID)> & <Second Alternate Coding System Version ID (ST)> & <Coding System OID (ST)> & <Value Set OID (ST)> & <Value Set Version ID (DTM)> & <Alternate Coding System OID (ST)> & <Alternate Value Set OID (ST)> & <Alternate Value Set Version ID (DTM)> & <Second Alternate Coding System OID (ST)> & <Second Alternate Value Set OID (ST)> & <Second Alternate Value Set Version ID (DTM)>

Definition: This field is used to communicate parameters and preferences to the filler application regarding the selection of an appropriate location for the appointment. The first component of this field is a code identifying the parameter or preference being passed to the filler application. The second component is the actual data value for that parameter.

Refer to Section _10.6.8.1_, "_APR-1 Time Selection Criteria (SCV) 00908_," for an example illustrating how this mechanism works within an interface.

The valid set of preferences should be determined by the placer and filler applications during implementation of the interface. Refer to file:///E:\\V2\\v2.9%20final%20Nov%20from%20Frank\\V29_CH02C_Tables.docx#HL70294[_User-defined Table 0294 - Time Selection Criteria Parameter Class Codes_] in Chapter 2C, Code Tables, for suggested examples.

