==== 4.5.6.7 IPC-7 Scheduled Station Name (EI) 01663

Components: <Entity Identifier (ST)> ^ <Namespace ID (IS)> ^ <Universal ID (ST)> ^ <Universal ID Type (ID)>

Definition: This field identifies the instance of the modality resource being requested for the performance of a particular Scheduled Procedure Step. It is a case of the Entity Identifier data type (section 2.A.28). The first component of this field is a string that identifies the particular piece of equipment. A limit of sixteen (16) characters is required to allow compatibility with DICOM. See DICOM Standard Part 3 for further details on DICOM Attribute (0040,0010) that conveys information identical to the component one of this field.

The second through fourth components identify the organization, in the form of the HD data type (see section 2.A.36, "HD - hierarchic designator").

If the Scheduled Procedure Step is to be performed by an unspecified member of a pool of resources, this field shall be empty and IPC-8 Scheduled Procedure Step Location is used to identify the site-specific resource pool. See section _4.5.6.8_, "_IPC-8 Scheduled Procedure Step_ Location (CWE) 01664," for explanation of the resource pool.

