==== 4.5.1.1 ORC-1 Order Control (ID) 00215

Definition: Determines the function of the order segment. Refer to E:\\V2\\v2.9 final Nov from Frank\\V29_CH02C_Tables.docx#HL70119[HL7 Table 0119 – Order Control Codes] in Chapter 2C, Code Tables, for valid entries. Depending on the message, the action of the control code may refer to an order or an individual service. For example, the code CA in an OMP message cancels the order. The same code in an RDS message, cancels the dispense. Very detailed explanatory notes are given at the end of this section.

This field may be considered the "trigger event" identifier for orders. The codes fall roughly into the following three categories:

{empty}a) event request – Codes like "NW" (new order) and "CA" (cancel order request) are used to initiate an event .

{empty}b) event acknowledgment – Codes like "OK" (order accepted) and "CR" (canceled as requested) are used to reply to the event request .

{empty}c) event notification – Codes like "OC" (order canceled) and "OD" (order discontinued) are used to notify other applications that an event has occurred. No application reply is necessary.

Event request codes are intended to initiate an event. Event acknowledgment codes are intended to reply to an application that requested an event. Event notification codes are intended to notify another application that, e.g., the filler has performed some action on an order that the other application, e.g., the placer, needs to know.

Fillers, placers, and other applications can use event requests, event acknowledgments, and event – notification-type trigger events interchangeably. However, certain order control codes can originate only from the filler (e.g., CR) and others can only originate from the placer (e.g., CA).

Refer file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70119[HL7 Table 0119 – Order Control Codes] in Chapter 2C, Code Tables__.__

