==== 4.5.1.8 ORC-8 Parent Order (EIP) 00222

Components: <Placer Assigned Identifier (EI)> ^ <Filler Assigned Identifier (EI)>

Subcomponents for Placer Assigned Identifier (EI): <Entity Identifier (ST)> & <Namespace ID (IS)> & <Universal ID (ST)> & <Universal ID Type (ID)>

Subcomponents for Filler Assigned Identifier (EI): <Entity Identifier (ST)> & <Namespace ID (IS)> & <Universal ID (ST)> & <Universal ID Type (ID)>

Definition: This field relates a child order to its parent order when a parent child order relationship exists. The parent child order mechanism is described in HL7 Table 0119 under order control code PA. This field uniquely identifies the parent order; no other information is required to link the child order with its parent order. It can be used to link the order to the results that triggered this order (e.g., a reflex order) or other order it relates to as an occurrence. This field repeats to allow linking to more than one parent, if necessary.

The first component has the same format as ORC-2-Placer Order Number (Section _link:#_OBR-2___Placer order number   (EI) [4.5.3.2],_ "link:#_OBR-2___Placer order number   (EI) [_Placer Order Number_ (EI) 00216]"). The second component has the same format as ORC-3-Filler Order Number (Section link:#_OBR-3___Filler Order Number   (EI) [_4.5.3.3_], "link:#_OBR-3___Filler Order Number   (EI) [_Filler Order Number_ (EI) 00217]"). The components of the placer order number and the filler order number are transmitted in sub‑components of the two components of this field.

Note that ORC-8 – Parent Order is equivalent to OBR-54 – Parent Order, but neither one is the same as OBR-29 – Result Observation Identifier.

Condition: Where the message has matching ORC/OBR pairs, ORC-8 and OBR-54 Must carry the same value.

