==== 6.5.7.27 NOTE: US Realm guidance. The term subscriber typically refers to to an individual or entity that selects benefits offered by an entity, such as an employer, government, or insurance company. In Government Social Programs such as Medicare and Medicaid enrollees are not considered subscribers and do not have dependents. However, government or commercial payers may treat these enrollees as subscribers in their systems, e.g., for coordination of benefits or providing managed care for a government program. The assigning authority and identifier type code are strongly recommended for all CX data types.IN2-27 Eligibility Source (CWE) 00498

Components: <Identifier (ST)> ^ <Text (ST)> ^ <Name of Coding System (ID)> ^ <Alternate Identifier (ST)> ^ <Alternate Text (ST)> ^ <Name of Alternate Coding System (ID)> ^ <Coding System Version ID (ST)> ^ <Alternate Coding System Version ID (ST)> ^ <Original Text (ST)> ^ <Second Alternate Identifier (ST)> ^ <Second Alternate Text (ST)> ^ <Name of Second Alternate Coding System (ID)> ^ <Second Alternate Coding System Version ID (ST)> ^ <Coding System OID (ST)> ^ <Value Set OID (ST)> ^ <Value Set Version ID (DTM)> ^ <Alternate Coding System OID (ST)> ^ <Alternate Value Set OID (ST)> ^ <Alternate Value Set Version ID (DTM)> ^ <Second Alternate Coding System OID (ST)> ^ <Second Alternate Value Set OID (ST)> ^ <Second Alternate Value Set Version ID (DTM)>

Definition: Identifies the source of information about the insured's eligibility for benefits. Refer to User-defined Table 0144 - Eligibility Source in Chapter 2C, Code Tables, for suggested values.

