==== 6.5.16.8 GP2-8 Modifier Edit Code (CWE) 01610

Components: <Identifier (ST)> ^ <Text (ST)> ^ <Name of Coding System (ID)> ^ <Alternate Identifier (ST)> ^ <Alternate Text (ST)> ^ <Name of Alternate Coding System (ID)> ^ <Coding System Version ID (ST)> ^ <Alternate Coding System Version ID (ST)> ^ <Original Text (ST)> ^ <Second Alternate Identifier (ST)> ^ <Second Alternate Text (ST)> ^ <Name of Second Alternate Coding System (ID)> ^ <Second Alternate Coding System Version ID (ST)> ^ <Coding System OID (ST)> ^ <Value Set OID (ST)> ^ <Value Set Version ID (DTM)> ^ <Alternate Coding System OID (ST)> ^ <Alternate Value Set OID (ST)> ^ <Alternate Value Set Version ID (DTM)> ^ <Second Alternate Coding System OID (ST)> ^ <Second Alternate Value Set OID (ST)> ^ <Second Alternate Value Set Version ID (DTM)>

Definition: This field contains calculated edits of the modifiers for each line or HCPCS/CPT. This field can be repeated up to five times, one edit for each of the modifiers present. This field relates to the values in link:#pr1-16-procedure-code-modifier-cne-01316[_PR1-16 - Procedure Code Modifier_]. Each repetition corresponds positionally to the order of the PR1-16 modifier codes. If no modifier code exists, use the code "U" (modifier edit code unknown) as a placeholder. The repetitions of Modifier Edit Codes must match the repetitions of Procedure Code Modifiers. For example, if link:#pr1-16-procedure-code-modifier-cne-01316[_PR1-16 - Procedure Code Modifier_] reports ...|01~02~03~04|... as modifier codes, and modifier code 03 modifier status code is unknown, _GP2-8 - Modifier Edit Code_ would report ...|1~1~U~1|... Refer to file:///E:\V2\V29_CH02C_Tables.docx#HL70467[_User-defined table 0467 -_ _Modifier Edit Code_] in Chapter 2C, Code Tables, for suggested values. This field is defined by CMS or other regulatory agencies

