=== 3.4.19 GSP – Person Gender and Sex Segment

It is imperative that both sex and gender vocabulary be formally integrated into clinical care because they are not interchangeable. Both influence health outcomes. Gender-marginalized individuals face significant barriers to adequate and culturally responsive healthcare, leading to numerous health disparities. The single field PID-8 Sex with user-defined values was renamed in V2.4 (2000) to Administrative Sex in recognition that it was insufficient or inappropriate for conveying Sex Parameter for Clinical Use. There are now several fields in HL7 v2 that support communicating administrative sex values for various actors; PID-8 for the patient’s Administrative Sex, IN1-43 for the Insured’s Administrative Sex, GT1-9 for the Guarantor’s Administrative Sex, NK1-15 for the Next of Kin / Associated Party’s Administrative Sex, etc. It is widely recognized that the concept of Administrative Sex is not clearly defined and is very widely overloaded with other concepts in real-world implementations. The following segments Person Gender and Sex (GSP), Recorded Gender and Sex (GSR) and Sex Parameter for Clinical Use (GSC) address this gap by placing them inside the message structure in a way that provides the context, e.g. following the Patient segments (PID, PD1, PD2), the Next-of-Kin segment (NK1) or the Guarantor (GT1) segment, etc.

The GSP segment conveys person-level concepts relating to an individual. Common concepts known to be important include:

____
• Gender Identity which is an individual's personal sense of being a man, woman, boy, girl, nonbinary, or something else. This datum represents an individual’s identity, ascertained by asking them what that identity is.

• Personal Pronouns which indicate the pronoun(s) specified by the individual to use when referring to the person in speech, in clinical notes, in written instructions and in other communications. Avoiding incorrect pronoun use and person misgendering is crucial in transgender and gender-diverse care. It is important to reliably exchange personal pronouns that the individual has specifically reported they want used. Different pronouns may be used in one care setting than another care setting. The pronouns used in the work environment may be different than those in the care setting.

• Sexual Orientation specifies a person’s identification of their emotional, romantic, sexual, or affectional attraction to another person.

The HL7 base specification does not prescribe if/how a system maintains an audit trail of changes to the data represented in the GSP segment. Depending on system design and workflow needs, it may be necessary to retain the gender and sex history for an individual.

The use of the GSP segment is not restricted to use with a patient alone. Other individuals represented in a message (e.g. a next of kin or staff) may also have personal gender and sex values.
____

HL7 Attribute Table – GSP – Person Gender and Sex

[width="100%",cols="14%,6%,7%,6%,6%,6%,7%,7%,41%",options="header",]
|===
|SEQ |LEN |C.LEN |DT |OPT |RP/# |TBL# |ITEM# |ELEMENT NAME
|1 | | |SI |R | | |03543 |Set ID
|2 |1..1 | |ID |R | |0206 |00816 |Action Code
|3 | | |EI |C | | |02510 |GSP Instance Identifier
|4 | | |CWE |R | |0820 |02511 |SOGI Concept
|5 | | |CWE |R | |0821, 0822, 0823 |02512 |SOGI Concept Value
|6 | | |DR |O | | |02513 |Validity Range
|7 | | |TX |O | | |02514 |Comment
|===

