==== 8.10.3.4 PRC-4 Valid Patient Classes (CWE) 00967

Components: <Identifier (ST)> ^ <Text (ST)> ^ <Name of Coding System (ID)> ^ <Alternate Identifier (ST)> ^ <Alternate Text (ST)> ^ <Name of Alternate Coding System (ID)> ^ <Coding System Version ID (ST)> ^ <Alternate Coding System Version ID (ST)> ^ <Original Text (ST)> ^ <Second Alternate Identifier (ST)> ^ <Second Alternate Text (ST)> ^ <Name of Second Alternate Coding System (ID)> ^ <Second Alternate Coding System Version ID (ST)> ^ <Coding System OID (ST)> ^ <Value Set OID (ST)> ^ <Value Set Version ID (DTM)> ^ <Alternate Coding System OID (ST)> ^ <Alternate Value Set OID (ST)> ^ <Alternate Value Set Version ID (DTM)> ^ <Second Alternate Coding System OID (ST)> ^ <Second Alternate Value Set OID (ST)> ^ <Second Alternate Value Set Version ID (DTM)>

Definition: This field contains the patient types for which this charge description is valid. For example, Inpatient, Outpatient, Series, Clinic, ER, Ambulatory, Observation, etc. These values should be the same set of values as those used for _PV1-3 - Patient Class_, which is site defined. Use only when the price is not valid for all patient types, that is, a null value indicates that this pricing is valid for all patient classes. Refer to file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70004[User-defined Table 0004 - Patient Class] in Chapter 2C, Code Tables, for suggested values.

When two PRC segments are sent the same key values but with different valid patient classes, the second is sent in addition to the first, not to replace the first. The effective unique identifier is the charge code (_PRC-1 - PRC Primary Key_) plus the facility ID (_PRC-2 - Facility ID_) plus the department (_PRC-3 - Department_) plus the patient class (_PRC-4 - Valid Patient Classes_). Multiple patient classes can be sent in the same segment to indicate that those patient classes use the same pricing.

