==== 8.8.10.6 OM2-6 Reference (Normal) Range for Ordinal and Continuous Observations (RFR) 00631

Components: <Numeric Range (NR)> ^ < Sex (CWE)> ^ <Age Range (NR)> ^ <Gestational Age Range (NR)> ^ <Species (ST)> ^ <Race/subspecies (ST)> ^ <Conditions (TX)>

Subcomponents for Numeric Range (NR): <Low Value (NM)> & <High Value (NM)>

Subcomponents for Sex (CWE): <Identifier (ST)> & <Text (ST)> & <Name of Coding System (ID)> & <Alternate Identifier (ST)> & <Alternate Text (ST)> & <Name of Alternate Coding System (ID)> & <Coding System Version ID (ST)> & <Alternate Coding System Version ID (ST)> & <Original Text (ST)> & <Second Alternate Identifier (ST)> & <Second Alternate Text (ST)> & <Name of Second Alternate Coding System (ID)> & <Second Alternate Coding System Version ID (ST)> & <Coding System OID (ST)> & <Value Set OID (ST)> & <Value Set Version ID (DTM)> & <Alternate Coding System OID (ST)> & <Alternate Value Set OID (ST)> & <Alternate Value Set Version ID (DTM)> & <Second Alternate Coding System OID (ST)> & <Second Alternate Value Set OID (ST)> & <Second Alternate Value Set Version ID (DTM)>

Subcomponents for Age Range (NR): <Low Value (NM)> & <High Value (NM)>

Subcomponents for Gestational Age Range (NR): <Low Value (NM)> & <High Value (NM)>

Definition: This field contains the reference (normal) ranges for "numeric" observations/tests with a nature code of A or C (see _OM1-18 - Nature of Service/Test/Observation_). It can identify different reference (normal) ranges for different categories of patients according to age, sex, race, and other conditions.

In the first component of this field (Normal Range (NR)), the units are assumed to be identical to the reporting units given in _OM2-2 - Units of Measure_.

When two different methods result in two different reference ranges, two different observations and corresponding OMx segments should be defined.

