==== 8.8.9.58 OM1-58 Gender Restriction (CWE) 03439

Components: <Identifier (ST)> ^ <Text (ST)> ^ <Name of Coding System (ID)> ^ <Alternate Identifier (ST)> ^ <Alternate Text (ST)> ^ <Name of Alternate Coding System (ID)> ^ <Coding System Version ID (ST)> ^ <Alternate Coding System Version ID (ST)> ^ <Original Text (ST)> ^ <Second Alternate Identifier (ST)> ^ <Second Alternate Text (ST)> ^ <Name of Second Alternate Coding System (ID)> ^ <Second Alternate Coding System Version ID (ST)> ^ <Coding System OID (ST)> ^ <Value Set OID (ST)> ^ <Value Set Version ID (DTM)> ^ <Alternate Coding System OID (ST)> ^ <Alternate Value Set OID (ST)> ^ <Alternate Value Set Version ID (DTM)> ^ <Second Alternate Coding System OID (ST)> ^ <Second Alternate Value Set OID (ST)> ^ <Second Alternate Value Set Version ID (DTM)>

Definition: This field is used to convey gender restrictions for ordering the test specified in OM1-2 Producer's Service/Test/Observation ID. If there are no restrictions the field is left empty. If the test is restricted to order for certain gender(s), the restricted genders are listed. For example, a Prostate Specific AG (PSA) test is typically ordered only for male patients, thus for PSA the field would be valued 'M' for Male.

Note that the field name is historical as gender restriction for procedures and laboratory tests are based upon Sex Parameter for Clinical Use. Refer to User-defined Table 0001 Administrative Sex – or 0828Sex Parameter for Clinical Use in Chapter 2C, Code Tables, for suggested values.

