==== 8.8.9.44 OM1-44 Challenge Information (TX) 00939

Definition: This optional attribute provides information for classifying observations by the challenge component of the test, if a challenge does speciate the observation. For example, distinguishing tests that have a challenge component in database. There co-ascribes the physiologic or drug challenge that is intrinsic to the measurement. To identify, for example, tests that include a glucose challenge.

To construct this text string, use the following template. (Note: This field is not constructed of formally defined components; it is a free text field. Component delimiters are not used and it is not necessary to supply placeholders if some "components" are not used.)

The time delay follows the syntax: n<S|M|H|D|W> where n is a number (possibly a decimal); S denotes seconds; M denotes minutes; H denotes hours; D denotes days; and W denotes weeks. The time delay can be preceded by a 'greater than' (>) sign, e.g. >4H.

file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70256[HL7 Table 0256 - Time Delay Post Challenge] in Chapter 2C, Code Tables, lists possible values for time delay.

Examples:

PRE 100 GM GLUCOSE PO

PRE 100 GM GLUCOSE PO

30M POST 100 GM GLUCOSE PO

2H POST 100 GM GLUCOSE PO

TROUGH

For drug peak and trough measures the nature of the substance challenged is the same as the analyte name, and need not be included.

We denote the route of the challenge via abbreviations for medication routes (see Chapter 4A, section 4A.4.2.1, "Route," which references file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70162[HL7 Table 0162 - Route of Administration] in Chapter 2C, Code Tables). An oral route of administration would be denoted by "PO," an intravenous route by "IV."

Details of the drug dose, time the dose was given, route of administration, etc., would be noted in separate OBX, and would have corresponding master observation definitions stored in the observation master file map to different records stored in the master file segments contained in the drug level message.

The nature of a physiologic (non-drug) challenge may also be specified, using the terms in file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70257[HL7 Table 0257 - Nature of challenge] in Chapter 2C, Code Tables.

