==== 8.8.9.50 OM1-50 Taxonomic Classification Code (CWE) 01539

Components: <Identifier (ST)> ^ <Text (ST)> ^ <Name of Coding System (ID)> ^ <Alternate Identifier (ST)> ^ <Alternate Text (ST)> ^ <Name of Alternate Coding System (ID)> ^ <Coding System Version ID (ST)> ^ <Alternate Coding System Version ID (ST)> ^ <Original Text (ST)> ^ <Second Alternate Identifier (ST)> ^ <Second Alternate Text (ST)> ^ <Name of Second Alternate Coding System (ID)> ^ <Second Alternate Coding System Version ID (ST)> ^ <Coding System OID (ST)> ^ <Value Set OID (ST)> ^ <Value Set Version ID (DTM)> ^ <Alternate Coding System OID (ST)> ^ <Alternate Value Set OID (ST)> ^ <Alternate Value Set Version ID (DTM)> ^ <Second Alternate Coding System OID (ST)> ^ <Second Alternate Value Set OID (ST)> ^ <Second Alternate Value Set Version ID (DTM)>

Definition: The species of living organism. This may include the common or scientific name, based on the coding system(s) used. SNOMED is the recommended coding system. If this field is not valued, a human is assumed. Refer to Table 0661 - Taxonomic Classification Code in Chapter 2C for valid values.

For example:

...|L-80700^Canine, NOS^SNM3|...

...|L-80100^Bovine^SNM3|...

...|L-80A00^Feline^SNM3|....

This field is a list of species or other taxonomic classification(s) to which the indicated specimen type may appropriately be applied for the indicated observation or test. If this field is omitted the default meaning is that the test or observation is applicable to humans. In a veterinary context if the test is applicable to any species, an appropriate code such as "Kingdom Animalia (organism)" should be used to avoid confusion with the meaning of human only.

