=== 2A.2.5 CD - channel definition

*Attention: _Retained for backward compatibility onlyas of v 2.7_.* This is used only in the waveform message, CHM category, which has been retained for backward compatibility only in v 2.7.

HL7 Component Table - CD – Channel Definition

[width="99%",cols="10%,7%,8%,6%,7%,7%,32%,13%,10%",options="header",]
|===
|SEQ |LEN |C.LEN |DT |OPT |TBL# |COMPONENT NAME |COMMENTS |SEC.REF.
|1 | | |WVI |O | |Channel Identifier | |2A.2.85
|2 | | |WVS |O | |Waveform Source | |2A.2.86
|3 | | |CSU |O | |Channel Sensitivity and Units | |2A.2.12
|4 | | |CCP |O | |Channel Calibration Parameters | |2A.2.4
|5 | |6# |NM |O | |Channel Sampling Frequency | |2A.2.47
|6 | | |NR |O | |Minimum and Maximum Data Values | |2A.2.48
|===

Definition: This data type is used for labeling of digital waveform data. It defines a recording channel, which is associated with one of the values in each time sample of waveform data. Each channel has a number (which generally defines its position in a multichannel display) and an optional name or label (also used in displays). One or two named waveform sources may also be associated with a channel (providing for the use of differential amplifiers with two inputs). The other components of the channel definition data type are optional. The individual components are defined as follows:

