==== 4A.4.1.1 RXO-1 Requested Give Code (CWE) 00292

Components: <Identifier (ST)> ^ <Text (ST)> ^ <Name of Coding System (ID)> ^ <Alternate Identifier (ST)> ^ <Alternate Text (ST)> ^ <Name of Alternate Coding System (ID)> ^ <Coding System Version ID (ST)> ^ <Alternate Coding System Version ID (ST)> ^ <Original Text (ST)> ^ <Second Alternate Identifier (ST)> ^ <Second Alternate Text (ST)> ^ <Name of Second Alternate Coding System (ID)> ^ <Second Alternate Coding System Version ID (ST)> ^ <Coding System OID (ST)> ^ <Value Set OID (ST)> ^ <Value Set Version ID (DTM)> ^ <Alternate Coding System OID (ST)> ^ <Alternate Value Set OID (ST)> ^ <Alternate Value Set Version ID (DTM)> ^ <Second Alternate Coding System OID (ST)> ^ <Second Alternate Value Set OID (ST)> ^ <Second Alternate Value Set Version ID (DTM)>

Definition: This field identifies the treatment product or treatment ordered to be given to the patient; it is analogous to _OBR-4-universal service ID_ in function. Examples of treatments products include medications and certain devices or supplies, e.g., inhaler spacers, blood glucose monitors, syringes, infusion sets, which might require prescription. Refer to Table 0747 - Requested Give Code in Chapter 2C for valid values.

Often the coded entry implies dosage form and a dosage form is required in addition to the product name. When the give code does not include the dosage form, use _RXO-5-requested dosage form_. When the give code does not include the strength, use _RXO-18-requested give strength_ and the _RXO-19-requested give units. Realize that strengths do not apply to some such orders._

The RXO-1, RXO-2 and RXO-4 are mandatory unless the prescription/treatment is transmitted as free text using RXO-6; then RXO-1, RXO-2, and RXO-4 may be blank and the first subcomponent of RXO-6 must be blank.

Use of the RXO-6.2 versus the RXO-1.2 for a free text order is dependent on whether or not the free text describes a product or if it is more commentary in nature.

Please refer to the request –to-dispense fields RXO-10, RXO-11, and RXO-12 for a discussion of the interrelationship with the request-to-give fields.

