==== 4A.4.1.17 RXO-17 Requested Give Per (Time Unit) (ST) 00308

Definition: This field identifies the time unit to use to calculate the rate at which the pharmaceutical is to be administered.

Format:

[width="100%",cols="32%,11%,57%",]
|===
|S<integer> |= |<integer> seconds
|M<integer> |= |<integer> minutes
|H<integer> |= |<integer> hours
|D<integer> |= |<integer> days
|W<integer> |= |<integer> weeks
|L<integer> |= |<integer> months
|===

*Note:* This is the same as the format specified for the DURATION component of the quantity/timing field, excluding the "X" specification.

This field is defined as conditional because it is required when the ordered substance is to be administered continuously at a prescribed rate (e.g., certain IVs). For example, if the "give amount/units" are 300 ml and the "give per" time unit is H1, the rate is 300ml/hr and the duration of this dose is 1 hour. Thus the give amount and give per time unit define the duration of the service.

This field is distinct from the "interval" component of the quantity/timing field, but it could be used in conjunction with it, as in _give 300ml of NS per hr for 1 hour, repeat twice a day_.

