==== 4A.4.1.30 RXO-30 Segment Instance Identifier (EI) 02150

Components: <Entity Identifier (ST)> ^ <Namespace ID (IS)> ^ <Universal ID (ST)> ^ <Universal ID Type (ID)>

Definition: This field contains a value that uniquely identifies this segment across time and messages. This is not intended as a "Set ID", but as a unique identifier allowing references not only to segments of the same message, but also to segments of other messages and indirectly to the entities described in those segments if the necessary persistence was manageable by the applications. This identifier is persistent within and across message instances.

Note: RXO-30 Segment Instance Identifier was introduced in v 2.6 to support Patient Care messaging concepts and constructs. At this time, there are no documented use cases for this field in the context of a pharmacy/treatment orders as described in this chapter. This statement does not preclude the use of RXO-30 in pharmacy messages, but implementers should exercise caution in using this field outside of the Patient Care context until the pharmacy/treatment use cases are established.

