==== 4A.4.4.22 RXE-22 Give Per (Time Unit) (ST) 00331

Definition: This field contains the time unit to use to calculate the rate at which the pharmaceutical is to be administered.

Format:

[width="100%",cols="17%,8%,75%",]
|===
|S<integer> |= |<integer> seconds
|M<integer> |= |<integer> minutes
|H<integer> |= |<integer> hours
|D<integer> |= |<integer> days
|W<integer> |= |<integer> weeks
|L<integer> |= |<integer> months
|T<integer> |= |at the interval and amount stated until a total of <integer> "DOSAGE" is accumulated. Units would be assumed to be the same as in the QUANTITY field.
|INDEF |= |do indefinitely - also the default
|===

This is the same as the format specified for the DURATION component of the quantity/timing field, excluding the "X" specification.

This field is defined as conditional because it is required when the ordered substance is to be administered continuously at a prescribed rate (e.g., certain IVs). For example, if the "give amount/units" were 300 ml and the "give per" time unit were H1 (equivalent to one hour), the rate is 300ml/hr.

