== 9.2 PURPOSE

This chapter currently supports document management. In the future, it is intended also to support the data exchange needs of applications supporting other medical record functions, including chart location and tracking, deficiency analysis, consents, and release of information. The main purpose of the medical record is to produce an accurate, legal, and legible document that serves as a comprehensive account of healthcare services provided to a patient.

Document/reports supported in this chapter will meet the criteria as described in Chapter 7, "Observations" (section 7.2 – Purpose). The appropriate use of MDM messages versus ORU message has been clarified in 7.2.

=== 9.2.1 Definition of Document Management Terms and Concepts

This section provides definitions of terms used throughout this chapter. The intent of this part is to provide clarification on use and interpretation.

==== 9.2.1.0 Addendum:

An appendage to an existing document that contains supplemental information. The parent document remains in place and its content is unaltered.

==== 9.2.1.1 Archived:

A storage status in which a document has been stored off-line for long-term access.

==== 9.2.1.2 Canceled:

An availability status in which a document has been "removed" from a patient's record with no replacement. This is done when a document has been erroneously created or assigned to the incorrect patient.

==== 9.2.1.3 Composite document:

A document which consists of an original document and one or more addenda.

==== 9.2.1.4 Document completion table:

The following terms are used to describe the workflow progression of a document:

===== 9.2.1.4.1 Authenticated:

A completion status in which a document or entry has been signed manually or electronically by one or more individuals who attest to its accuracy. No explicit determination is made that the assigned individual has performed the authentication. While the standard allows multiple instances of authentication, it would be typical to have a single instance of authentication, usually by the assigned individual.

===== 9.2.1.4.2 Dictated:

A completion status in which information has been orally recorded but not yet transcribed.

===== 9.2.1.4.3 Documented:

A completion status in which document content, other than dictation, has been received but has not been translated into the final electronic format. Examples include paper documents, whether hand-written or typewritten, and intermediate electronic forms, such as voice to text.

===== 9.2.1.4.4 In Progress/Assigned:

A workflow status in which the recipient has assigned the material to personnel to perform the task of transcription. The document remains in this state until the document is transcribed.

===== 9.2.1.4.5 Incomplete:

A completion status in which information is known to be missing from a document.

===== 9.2.1.4.6 Legally Authenticated:

A completion status in which a document or entry has been signed manually or electronically by the individual who is legally responsible for that document or entry. This is the most mature state in the workflow progression.

===== 9.2.1.4.7 Pre-Authenticated:

A completion status in which a document is transcribed but not authenticated.

==== 9.2.1.5 Edited Document:

A document that alters an existing document which had not been made available for patient care (see also Section _9.2.1.9_, "_Replacement Document:_").

==== 9.2.1.6 New or Original Document:

The first version of a document. The original may or may not be final or authenticated. An original document should have a set of associated statuses to define its current condition.

==== 9.2.1.7 Obsolete:

An availability status in which a document has been replaced by a document which contains revised content.

==== 9.2.1.8 Purged:

A storage status in which a document is no longer available in this system.

==== 9.2.1.9 Replacement Document:

A document that replaces an existing document. The original document becomes obsolete, but is still retained in the system for historical reference.

==== 9.2.1.10 Restricted:

A confidentiality status in which access to a document has institutionally assigned limitations.

==== 9.2.1.11 Revised document:

This is not a supported trigger event. See Sections _9.2.1.5_, "_Edited Document:_", and _9.2.1.9_ "_Replacement Document:_".

==== 9.2.1.12 Transcription:

A process of transforming dictated or otherwise documented information into an electronic format.

=== 9.2.2 Definition of Consent Terms and Concepts

==== 9.2.2.0 Background Text: 

In most cases in the health field, consent must be "informed" consent. This means that the consenting individual must understand and appreciate the implications of what he or she is consenting to. Most consent processes involve providing background material describing the reasons for the proposed service, expected benefits and potential risks. It is important to have a record of what information was presented to the subject at the time of consent.

==== 9.2.2.1 Consent Bypass Reason: 

There may arise situations in which an action must be performed without patient consent (i.e., retrieving an unconscious patient's drug history, performing life saving surgery, etc.). This field indicates the rationale for accessing information without obtaining the required consent.

==== 9.2.2.2 Consent Decision Date/Time: 

Related to the above, there also needs to be a record of the time the subject actually made their consent decision.

==== 9.2.2.3 Consent Disclosure Level: 

Identifies whether the subject was provided with information on the full background information on the procedure the subject is giving consent to; i.e., has all information needed for 'informed' consent been provided.

==== 9.2.2.4 Consent Discussion Date/Time: 

For informed consent, a knowledgeable person must discuss the ramifications of consent with the subject. In some instances, this discussion is required to take place prior to the provision of consent. This ensures that the subject has sufficient time to consider the ramifications of his or her decision. To ensure that guidelines are followed, it is imperative to record when the consent information was initially discussed with the subject.

==== 9.2.2.5 Consent Effective Date/Time: 

Not all consents take effect at the time the consent decision is made. They may not become effective for some time, or in certain circumstances they may even be retroactive. Use this field to record the effective time.

==== 9.2.2.6 Consent End Date/Time: 

For most programs requiring voluntary participation, the decision to participate is not final and therefore may be revoked in the future. Therefore, when a patient makes the decision to revoke his or her consent, the date and time on which the decision was made must be recorded in order to provide a complete history of the consent. Alternatively, the initial consent may only have been granted for a limited period of time (i.e., 24 hours, 1 week, 1 year). If Consent End Date/Time is null, this should be interpreted as 'indefinite.'

==== 9.2.2.7 Consent Form ID: 

Some institutions may have a set of pre-defined consent forms. Identifying the specific form identifies the details the subject is consenting to, as well as what information is on the form.

==== 9.2.2.8 Consent Mode: 

The manner in which consent can be given may vary greatly within a specific program, from program to program, or from organization to organization. Therefore, the standard must allow applications to identify how consent was obtained (i.e., verbally, written, etc.).

==== 9.2.2.9 Consent Non-disclosure Reason: 

Identifies why information was withheld from the patient (i.e., telling the patient may cause a worse outcome than performing the procedure).

==== 9.2.2.10 Consent Segment

The issue of patient consent has become more important, particularly in the tracking of consent for the release of or exchange of information. The pieces of information recorded when dealing with a patient consent tend to be similar, regardless of the purpose of the consent. This segment combines these pieces of information so that they can be used for consents of any type.

==== 9.2.2.11 Consent Status: 

Consent can be pending (subject hasn't been asked yet), given, refused, revoked or even completely bypassed. Consent Status identifies what the status of a subject's consent is (or was at a given point in time).

==== 9.2.2.12 Consent Text: 

When recording consents electronically it is important to know the specific text that was presented to the consenting person.

==== 9.2.2.13 Consent Type:

In concert with giving consent, some programs may allow patients to request varying degrees of participation in a given program. I.e., if a consent program relates to a patient's entire medical record being available online they might have the opportunity to only reveal certain portions of that history, such as the drug history only.

==== 9.2.2.14 Informational Material Supplied Indicator: 

As part of the informed consent process, additional material in the form of pamphlets, books, brochures, videos, etc., may be provided to the patient. An indication of whether this has been done is required. (Details on the materials provided will be sent using a separate segment.)

==== 9.2.2.15 Subject Competence Indicator: 

One of the issues involved in informed consent is whether the subject is judged to be competent to provide consent on his or her own behalf. Factors involve age, mental capacity, and current state of health/awareness. A professional judgment about whether the subject is deemed competent must be made and recorded.

==== 9.2.2.16 Subject-imposed Limitations: 

At the time of consent, the subject may wish to make modifications or add limitations to his or her consent. These modifications and limitations must be recorded.

==== 9.2.2.17 Subject-specific Background Text: 

The reasons, expected benefits and risks may vary from subject to subject. It may be necessary to inform the subject of background information that only applies to his or her particular circumstance.

==== 9.2.2.18 Subject-specific Consent Text: 

Sometimes consent forms have areas where details of the procedure or information distribution that are specific to a given consent instance are recorded, i.e., a variation on a common procedure, or an explicit listing of documents to be released. As this is part of the consent document, it needs to be recorded. It is helpful to keep this information separate from the standard 'template' consent text, as in most circumstances people viewing the consent will want to know "What's different from usual?"

==== 9.2.2.19 Translation Type: 

To obtain informed consent, the patient must understand what he or she is consenting to. For subjects who do not understand the commonly used language of the institution, or who are unable to hear/read/speak, translation services may be required. An indication of what type(s) of translation were/will be performed is required.

==== 9.2.2.20 Translator Assistance Indicator: 

To obtain informed consent, the patient must understand what he or she is consenting to. For subjects who do not understand the commonly used language of the institution, or who are unable to hear/read/speak, translation services may be required.

== 9.3 DOCUMENT MANAGEMENT SECTION

This section defines the Medical Document Management (MDM) transaction set. It supports transmission of new or updated documents or information about their status(es). The trigger events and messages may be divided into two broad categories. One which describes the status of a document only and the other that describes the status and contains the document content itself.

The document management section is concerned primarily with the management of those documents and entries which are created as a result of a transcription process. Documents may be represented as a CDA document. See ANSI/HL7 CDA R2.0-2005 Section 3 for the correct method of transmitting CDA documents within an MDM message. These documents are created in two distinct contexts, one of which is related to an order and describes the procedures or activities associated with that order, and another which occurs independently of the order process. In this version we have added the ORC, OBR and associated NTE segments in order to provide full ordering context when appropriate for document management messages. The scope of this section also includes any document that contains data derived from orders or results but which must be treated as aggregate display data due to system limitations. This is a transition strategy to support integration of data across the continuum of care.

The content of a document can be represented with one or more observation segments (OBX). Where headings or separations naturally exist within the text, it is preferred that each of these blocks be represented as a separate OBX record. *Where systems are able to decompose the text into separate medical concepts, the most atomic level of granularity of content should be represented, ideally with each medical concept being represented in its own OBX segment*. Many of these concepts can be represented as coded entities.

== 9.4 Consent information

=== 9.4.1 Example 1

A patient decides to participate in a voluntary electronic drug history program. The patient records this decision in writing (Consent Mode) on a pre-designed consent form (Consent Form ID and Version) after the patient's health care service provider has explained the benefits and drawbacks of their participation (Consent Discussion Date/Time). In providing consent, the patient can also decide on the degree to which he or she will participate in the program (Consent Type). The consent decision (Consent Status) is recorded under the patient's name (use ROL segment) and the number of the paper-based form that the patient signed is recorded in the electronic consent gathering function (Consent Number). The patient's consent is effective from the day of the decision (Consent Effect Date/Time), but this consent can be terminated at the patient's discretion at a given date in the future (Consent End Date/Time). Several months later the patient is rushed into an emergency health care facility with what appears to be a drug reaction. While checking the patient's drug history, health care service providers find that the patient's drug history has controlled access. The patient is unable to provide access to this information given that patient's physical state, so the health care service provider circumvents the consent process (Non-consent Access Reason) in the interests of the patient's immediate well-being.

Example 2: A patient is seeking a therapeutic abortion. Because she is under 18, the practitioner must evaluate her competence to provide consent. The patient is deemed to be competent (*Patient Competence Indicator*). Local legislation mandates that the patient be counseled at least 24 hours prior to receiving the procedure. The patient is counseled, and the time recorded (*Consent Discussion Date/Time*). She is also given a pamphlet to take home and read (*Informational Material Supplied Indicator*). She returns the following day and signs the consent form (*Consent Decision Date/Time*).

Example 3: A deaf patient is admitted for labor and delivery. It becomes apparent the patient will require a cesarean section. A translator is required (*Translator Assistance Indicator*) who can translate sign language (*Translation Type*). The translator explains the details of the procedure the patient is being asked to consent to (*Consent Text*), the intention to use epidural anesthetic (*Subject-specific Consent Text*), the general risks associated with doing the procedure, as well as those with not doing the procedure (*Background Text*) and benefits associated with the epidural (*Subject-specific Background Text*). The patient agrees to the procedure, subject to the condition that she not be given any blood products for religious reasons (*Subject-imposed Limitations*).

Example 4: An employee signs a consent form authorizing (*Consent Status*) a hospital to request the employee's driving records from the local Department of Motor Vehicles (*Consent Type*).

Example 5: A patient signs a consent form to have basic diagnostic and billing information sent to that patient's insurer. The consent indicates that information may only be given to parties that are bound by HIPPA guidelines (*Trust Agreement Restriction Type*).

== 9.5 ASSUMPTIONS

Within this section we have created a single message whose contents vary predicated on the trigger event. The following assumptions are made when the Medical Document Management (MDM) message is used:

• The application system is responsible for meeting all legal requirements (on the local, state, and federal levels) in the areas of document authentication, confidentiality, and retention.

• All documents are unique, and document numbers and file names are not reused.

• Documents may be associated with one or more orders.

== 9.6 TRIGGER EVENTS AND MESSAGE DEFINITIONS

Each triggering event is listed below, along with the applicable form of the message exchange. The notation used to describe the sequence, optionality, and repetition of segments is described in Chapter 2, "Format for Defining Abstract Messages." There are two classes of events, those which contain notifications only, and those which contain both notifications and content (text contained in OBX segments).

*Note*: Note that the event is encapsulated in MSH-9 and the event segment is deprecated for all MDM message cases as of version 2.5.

When -MSH-9 is valued, the value of EVN-1 must be the same.

These triggering events are mainly associated with documents or entries that will be or have been transcribed. The types and appearance of the transcribed documents can vary greatly within a healthcare organization and between organizations. However, the main purpose of the transcription process is to document patient care or diagnostic results in a legible manner; these documents then become part of the legal medical record. The conceptual purpose of document notification is to facilitate updating the receiving system(s) with information from the source system(s), typically dictation or transcription systems, to indicate that an electronic document has been created or altered. The document notification message can be attached to an entire document (i.e., transcribed document) or can be transmitted stand-alone. In either case, the document notification is transmitted in the form of an unsolicited update or in response to a record-oriented query. A document notification message can be created under a variety of circumstances such as when: 1) dictation has been completed; 2) a document has been transcribed; or, 3) the status of a document has been changed, i.e., when a document has been authenticated.

Also, the orders represented by the ORC/OBR segments must be wholly and exclusively satisfied by the TXA/OBX content. "Wholly satisfied" means there are no other orders related to the TXA/OBX content other than those specified by the ORC/OBR segments. "Exclusively satisfied" means that the actions described by the ORC/OBR segments do not contain actions not addressed by the TXA/OBX content. Thus, the TXA/OBX context must satisfy all instances of ORC/OBR as indicated by _ORC-7 Quantity/Timing,_ _OBR-27 Quantity/Timing_ or the TQ1/ TQ2 segments.

• The placer order number may exist in the ORC, OBR and TXA. If valued in the ORC or OBR and the TXA is present, it should not be valued. If TXA is valued it should be ignored.

• The filler order number may exist in the ORC, OBR and TXA. If valued in the ORC or OBR and the TXA is present, it should not be valued. If TXA is valued it should be ignored.

• Generally the _OBR-32 Principal interpreter_ and the _TXA –22.1 Authentication person_ are conceptually the same. Normally only the _TXA-22.1_ should be valued. If both are valued, the _TXA-22.1_ takes precedence.

The _OBR-35 Transcriptionist_ and the _TXA –11 Transcriptionist_ are conceptually the same. Normally only the _TXA-11_ should be valued. If both are valued, the _TXA-11_ takes precedence.

=== 9.6.1 MDM/ACK - Original Document Notification (Event T01)

This is a notification of the creation of a document without the accompanying content. There are multiple approaches by which systems become aware of documents:

*Scenario A:* A document is dictated and chart tracking system is notified that it has been dictated and is awaiting transcription.

*Scenario B:* Dictation is transcribed and chart tracking system is notified that the document exists and requires authentication.

*Scenario C:* A provider orders a series of three X-rays. The radiologist dictates a single document which covers all three orders. Multiple placer numbers are used to identify each of these orders.

MDM^T01^MDM_T01: Original Document Notification

[width="100%",cols="33%,47%,9%,11%",options="header",]
|===
|Segments |Description |Status |Chapter
|MSH |Message Header | |2
|[\{SFT}] |Software Segment | |2
|[ UAC ] |User Authentication Credential | |2
|EVN |Event Type |B, v2.5 |3
|PID |Patient Identification | |3
|[ \{ GSP } ] |Person Gender and Sex | |3
|[ \{ GSR } ] |Recorded Gender and Sex | |3
|[ \{ GSC } ] |Sex Parameter for Clinical Use | |3
|[ \{ PRT } ] |Participation | |7
|PV1 |Patient Visit | |3
|[ \{ PRT } ] |Participation | |7
|[\{ |--- COMMON_ORDER begin | |
|ORC |Common order segment | |4
|[\{ PRT }] |Participation | |
|[\{ |--- TIMING begin | |
|TQ1 |Timing/Quantity | |4
|[\{TQ2}] |Timing/Quantity Order Sequence | |4
|}] |--- TIMING end | |
|OBR |Observation request segment | |4
|[\{ PRT }] |Participation | |7
|[\{ NTE }] |Notes and comments about the observation request (OBR) | |2
|}] |--- COMMON_ORDER end | |
|link:#TXA[TXA] |Document Notification | |9
|[\{CON}] |Consent Segment | |9
|===

[width="100%",cols="18%,25%,6%,17%,17%,17%",options="header",]
|===
|Acknowledgement Choreography | | | | |
|MDM^T01^MDM_T01 | | | | |
|Field name |Field Value: Original mode |Field value: Enhanced mode | | |
|MSH-15 |Blank |NE |AL, SU, ER |NE |AL, SU, ER
|MSH-16 |Blank |NE |NE |AL, SU, ER |AL, SU, ER
|Immediate Ack |ACK^T01^ACK |- |ACK^T01^ACK |- |ACK^T01^ACK
|Application Ack |- |- |- |ACK^T01^ACK |ACK^T01^ACK
|===

ACK^T01^ACK: General Acknowledgment

[width="100%",cols="33%,47%,9%,11%",options="header",]
|===
|Segments |Description |Status |Chapter
|MSH |Message Header | |2
|[\{ link:#SFT[SFT] }] |Software Segment | |2
|[ UAC ] |User Authentication Credential | |2
|MSA |Message Acknowledgment | |2
|[\{ link:#ERR[ERR] }] |Error Information | |2
|===

[width="100%",cols="23%,37%,10%,30%",options="header",]
|===
|Acknowledgement Choreography | | |
|ACK^T01^ACK | | |
|Field name |Field Value: Original mode |Field value: Enhanced mode |
|MSH-15 |Blank |NE |AL, SU, ER
|MSH-16 |Blank |NE |NE
|Immediate Ack |ACK^T01^ACK |- |ACK^T01^ACK
|Application Ack |- |- |-
|===

=== 9.6.2 MDM/ACK - Original Document Notification and Content (Event T02) 

This is a notification of the creation of a document with the accompanying content.

*Scenario A:* Dictation is transcribed and the chart tracking system is notified that the document exists and requires authentication. The content of the document is transmitted along with the notification.

*Scenario B:* A provider orders a series of three X-rays. The radiologist's dictation is transcribed in a single document, which covers all three orders. Multiple placer numbers are used to identify each of the orders within the single document message. The notification and document content are transmitted.

MDM^T02^MDM_T02: Original Document Notification & Content

[width="100%",cols="33%,47%,9%,11%",options="header",]
|===
|Segments |Description |Status |Chapter
|MSH |Message Header | |2
|[\{SFT}] |Software Segment | |2
|[ UAC ] |User Authentication Credential | |2
|EVN |Event Type |B, v2.5 |3
|PID |Patient Identification | |3
|[ \{ GSP } ] |Person Gender and Sex | |3
|[ \{ GSR } ] |Recorded Gender and Sex | |3
|[ \{ GSC } ] |Sex Parameter for Clinical Use | |3
|[ \{ PRT } ] |Participation | |7
|PV1 |Patient Visit | |3
|[ \{ PRT } ] |Participation Segment | |7
|[\{ |--- COMMON_ORDER begin | |
|ORC |Common order segment | |4
|[\{ PRT }] |Participation | |7
|[\{ |--- TIMING begin | |
|TQ1 |Timing/Quantity | |4
|[\{TQ2}] |Timing/Quantity Order Sequence | |4
|}] |--- TIMING end | |
|OBR |Observation request segment | |4
|[\{ PRT }] |Participation | |7
|[\{ NTE }] |Notes and comments about the observation (OBR) | |2
|}] |--- COMMON_ORDER end | |
|link:#TXA[TXA] |Document Notification | |9
|[\{CON}] |Consent Segment | |9
|\{ | | |
|link:#OBX[OBX] |Observation/Result (one or more required) | |7
|[\{ PRT }] |Participation | |7
|[\{ NTE }] |Notes and comments about the observation (OBX) | |2
|} | | |
|===

[width="100%",cols="18%,25%,6%,17%,17%,17%",options="header",]
|===
|Acknowledgement Choreography | | | | |
|MDM^T02^MDM_T02 | | | | |
|Field name |Field Value: Original mode |Field value: Enhanced mode | | |
|MSH-15 |Blank |NE |AL, SU, ER |NE |AL, SU, ER
|MSH-16 |Blank |NE |NE |AL, SU, ER |AL, SU, ER
|Immediate Ack |ACK^T02^ACK |- |ACK^T02^ACK |- |ACK^T02^ACK
|Application Ack |- |- |- |ACK^T02^ACK |ACK^T02^ACK
|===

ACK^T02^ACK: General Acknowledgment

[width="100%",cols="33%,47%,9%,11%",options="header",]
|===
|Segments |Description |Status |Chapter
|MSH |Message Header | |2
|[\{ link:#SFT[SFT] }] |Software Segment | |2
|[ UAC ] |User Authentication Credential | |2
|MSA |Message Acknowledgment | |2
|[\{ link:#ERR[ERR] }] |Error Information | |2
|===

[width="100%",cols="23%,37%,10%,30%",options="header",]
|===
|Acknowledgement Choreography | | |
|ACK^T02^ACK | | |
|Field name |Field Value: Original mode |Field value: Enhanced mode |
|MSH-15 |Blank |NE |AL, SU, ER
|MSH-16 |Blank |NE |NE
|Immediate Ack |ACK^T02^ACK |- |ACK^T02^ACK
|Application Ack |- |- |-
|===

=== 9.6.3 MDM/ACK - Document Status Change Notification (Event T03) 

This is a notification of a change in a status of a document without the accompanying content.

*Scenario:* A document is authenticated. Notification is sent to the chart tracking system and is used to update the document status from pre-authenticated to authenticated or legally authenticated.

A change in any of the following independent status characteristics would cause a message to be sent:

• Completion Status

• Confidentiality Status

• Availability Status (the Availability Status of "cancelled" is supported in T11 (document cancel notification) or T03)

• Storage Status

MDM^T03^MDM_T01: Document Status Change Notification

[width="100%",cols="33%,47%,9%,11%",options="header",]
|===
|Segments |Description |Status |Chapter
|MSH |Message Header | |2
|[\{SFT}] |Software Segment | |2
|[ UAC ] |User Authentication Credential | |2
|EVN |Event Type ( |B, v2.5 |3
|PID |Patient Identification | |3
|[ \{ GSP } ] |Person Gender and Sex | |3
|[ \{ GSR } ] |Recorded Gender and Sex | |3
|[ \{ GSC } ] |Sex Parameter for Clinical Use | |3
|[ \{ PRT } ] |Participation | |3
|PV1 |Patient Visit | |3
|[ \{ PRT } ] |Participation | |7
|[\{ |--- COMMON_ORDER begin | |
|ORC |Common order segment | |4
|[\{ PRT }] |Participation | |7
|[\{ |--- TIMING begin | |
|TQ1 |Timing/Quantity | |4
|[\{TQ2}] |Timing/Quantity Order Sequence | |4
|}] |--- TIMING end | |
|OBR |Observation request segment | |4
|[ \{ PRT } ] |Participation | |7
|[\{ NTE }] |Notes and comments about the OBR | |2
|}] |--- COMMON_ORDER end | |
|link:#TXA[TXA] |Document Notification | |9
|[\{CON}] |Consent Segment | |9
|===

[width="100%",cols="18%,26%,6%,17%,16%,17%",options="header",]
|===
|Acknowledgement Choreography | | | | |
|MDM^T03^MDM_T01 | | | | |
|Field name |Field Value: Original mode |Field value: Enhanced mode | | |
|MSH-15 |Blank |NE |AL, SU, ER |NE |AL, SU, ER
|MSH-16 |Blank |NE |NE |AL, SU, ER |AL, SU, ER
|Immediate Ack |ACK^T03^ACK |- |ACK^T03^ACK |- |ACK^T03^ACK
|Application Ack |- |- |- |ACK^T03^ACK |ACK^T03^ACK
|===

ACK^T03^ACK: General Acknowledgment

[width="100%",cols="33%,47%,9%,11%",options="header",]
|===
|Segments |Description |Status |Chapter
|MSH |Message Header | |2
|[\{ link:#SFT[SFT] }] |Software Segment | |2
|[ UAC ] |User Authentication Credential | |2
|MSA |Message Acknowledgment | |2
|[\{ link:#ERR[ERR] }] |Error Information | |2
|===

[width="100%",cols="23%,37%,10%,30%",options="header",]
|===
|Acknowledgement Choreography | | |
|ACK^T03^ACK | | |
|Field name |Field Value: Original mode |Field value: Enhanced mode |
|MSH-15 |Blank |NE |AL, SU, ER
|MSH-16 |Blank |NE |NE
|Immediate Ack |ACK^T03^ACK |- |ACK^T03^ACK
|Application Ack |- |- |-
|===

=== 9.6.4 MDM/ACK - Document Status Change Notification and Content (Event T04)

This is a notification of a change in a status of a document with the accompanying content.

*Scenario:* A document is authenticated. Notification is sent to the chart tracking system and is used to update the document status from pre-authenticated to authenticated or legally authenticated. The document content is also transmitted.

MDM^T04^MDM_T02: Document Status Change Notification & Content

[width="100%",cols="33%,47%,9%,11%",options="header",]
|===
|Segments |Description |Status |Chapter
|MSH |Message Header | |2
|[\{SFT}] |Software Segment | |2
|[ UAC ] |User Authentication Credential | |2
|EVN |Event Type |B, v2.5 |3
|PID |Patient Identification | |3
|[ \{ GSP } ] |Person Gender and Sex | |3
|[ \{ GSR } ] |Recorded Gender and Sex | |3
|[ \{ GSC } ] |Sex Parameter for Clinical Use | |3
|[ \{ PRT } ] |Participation | |7
|PV1 |Patient Visit | |3
|[ \{ PRT } ] |Participation Segment | |7
|[\{ |--- COMMON_ORDER begin | |
|ORC |Common order segment | |4
|[ \{ PRT } ] |Participation | |7
|[\{ |--- TIMING begin | |
|TQ1 |Timing/Quantity | |4
|[\{TQ2}] |Timing/Quantity Order Sequence | |4
|}] |--- TIMING end | |
|OBR |Observation request segment | |4
|[ \{ PRT } ] |Participation | |7
|[\{ NTE }] |Notes and comments about the OBR | |2
|}] |--- COMMON_ORDER end | |
|link:#TXA[TXA] |Document Notification | |9
|[\{CON}] |Consent Segment | |9
|\{ | | |
|link:#OBX[OBX] |Observation/Result (one or more required) | |7
|[ \{ PRT } ] |Participation | |7
|[\{ NTE }] |Notes and comments segment for OBX | |2
|} | | |
|===

[width="100%",cols="18%,26%,6%,17%,16%,17%",options="header",]
|===
|Acknowledgement Choreography | | | | |
|MDM^T04^MDM_T02 | | | | |
|Field name |Field Value: Original mode |Field value: Enhanced mode | | |
|MSH-15 |Blank |NE |AL, SU, ER |NE |AL, SU, ER
|MSH-16 |Blank |NE |NE |AL, SU, ER |AL, SU, ER
|Immediate Ack |ACK^T04^ACK |- |ACK^T04^ACK |- |ACK^T04^ACK
|Application Ack |- |- |- |ACK^T04^ACK |ACK^T04^ACK
|===

ACK^T04^ACK: General Acknowledgment

[width="100%",cols="33%,47%,9%,11%",options="header",]
|===
|Segments |Description |Status |Chapter
|MSH |Message Header | |2
|[\{ link:#SFT[SFT] }] |Software Segment | |2
|[ UAC ] |User Authentication Credential | |2
|MSA |Message Acknowledgment | |2
|[\{ link:#ERR[ERR] }] |Error Information | |2
|===

[width="100%",cols="23%,37%,10%,30%",options="header",]
|===
|Acknowledgement Choreography | | |
|ACK^T04^ACK | | |
|Field name |Field Value: Original mode |Field value: Enhanced mode |
|MSH-15 |Blank |NE |AL, SU, ER
|MSH-16 |Blank |NE |NE
|Immediate Ack |ACK^T04^ACK |- |ACK^T04^ACK
|Application Ack |- |- |-
|===

=== 9.6.5 MDM/ACK - Document Addendum Notification (Event T05)

This is a notification of an addendum to a document without the accompanying content.

*Scenario:* Author dictates additional information as an addendum to a previously transcribed document. A new document is transcribed. This addendum has its own new unique document ID that is linked to the original document via the parent ID. Addendum document notification is transmitted. This creates a composite document.

MDM^T05^MDM_T01: Document Addendum Notification

[width="100%",cols="33%,47%,9%,11%",options="header",]
|===
|Segments |Description |Status |Chapter
|MSH |Message Header | |2
|[\{SFT}] |Software Segment | |2
|[ UAC ] |User Authentication Credential | |2
|EVN |Event Type |B, v2.5 |3
|PID |Patient Identification | |3
|[ \{ GSP } ] |Person Gender and Sex | |3
|[ \{ GSR } ] |Recorded Gender and Sex | |3
|[ \{ GSC } ] |Sex Parameter for Clinical Use | |3
|[ \{ PRT } ] |Participation | |7
|PV1 |Patient Visit | |3
|[ \{ PRT } ] |Participation Segment | |7
|[\{ |--- COMMON_ORDER begin | |
|ORC |Common order segment | |4
|[\{ PRT }] |Participation | |7
|[\{ |--- TIMING begin | |
|TQ1 |Timing/Quantity | |4
|[\{TQ2}] |Timing/Quantity Order Sequence | |4
|}] |--- TIMING end | |
|OBR |Observation request segment | |4
|[\{ PRT }] |Participation | |7
|[\{ NTE }] |Notes and comments about the OBR | |2
|}] |--- COMMON_ORDER end | |
|link:#TXA[TXA] |Document Notification | |9
|[\{CON}] |Consent Segment | |9
|===

[width="100%",cols="18%,26%,6%,17%,16%,17%",options="header",]
|===
|Acknowledgement Choreography | | | | |
|MDM^T05^MDM_T01 | | | | |
|Field name |Field Value: Original mode |Field value: Enhanced mode | | |
|MSH-15 |Blank |NE |AL, SU, ER |NE |AL, SU, ER
|MSH-16 |Blank |NE |NE |AL, SU, ER |AL, SU, ER
|Immediate Ack |ACK^T05^ACK |- |ACK^T05^ACK |- |ACK^T05^ACK
|Application Ack |- |- |- |ACK^T05^ACK |ACK^T05^ACK
|===

ACK^T05^ACK: General Acknowledgment

[width="100%",cols="33%,47%,9%,11%",options="header",]
|===
|Segments |Description |Status |Chapter
|MSH |Message Header | |2
|[\{ link:#SFT[SFT] }] |Software Segment | |2
|[ UAC ] |User Authentication Credential | |2
|MSA |Message Acknowledgment | |2
|[\{ link:#ERR[ERR] }] |Error Information | |2
|===

[width="100%",cols="23%,37%,10%,30%",options="header",]
|===
|Acknowledgement Choreography | | |
|ACK^T05^ACK | | |
|Field name |Field Value: Original mode |Field value: Enhanced mode |
|MSH-15 |Blank |NE |AL, SU, ER
|MSH-16 |Blank |NE |NE
|Immediate Ack |ACK^T05^ACK |- |ACK^T05^ACK
|Application Ack |- |- |-
|===

=== 9.6.6 MDM/ACK - Document Addendum Notification and Content (Event T06)

This is a notification of an addendum to a document with the accompanying content.

*Scenario:* Author dictates additional information as an addendum to a previously transcribed document. A new document is transcribed. This addendum has its own new unique document ID that is linked to the original document via the parent ID. Addendum document notification is transmitted, along with the document content. This creates a composite document.

MDM^T06^MDM_T02: Document Addendum Notification & Content

[width="100%",cols="33%,47%,9%,11%",options="header",]
|===
|Segments |Description |Status |Chapter
|MSH |Message Header | |2
|[\{SFT}] |Software Segment | |2
|[ UAC ] |User Authentication Credential | |2
|EVN |Event Type |B, v2.5 |3
|PID |Patient Identification | |3
|[ \{ GSP } ] |Person Gender and Sex | |3
|[ \{ GSR } ] |Recorded Gender and Sex | |3
|[ \{ GSC } ] |Sex Parameter for Clinical Use | |3
|[ \{ PRT } ] |Participation | |7
|PV1 |Patient Visit | |3
|[ \{ PRT } ] |Participation Segment | |7
|[\{ |--- COMMON_ORDER begin | |
|ORC |Common order segment | |4
|[ \{ PRT } ] |Participation | |7
|[\{ |--- TIMING begin | |
|TQ1 |Timing/Quantity | |4
|[\{TQ2}] |Timing/Quantity Order Sequence | |4
|}] |--- TIMING end | |
|OBR |Observation request segment | |4
|[ \{ PRT } ] |Participation | |7
|[\{ NTE }] |Notes and comments about the OBR | |2
|}] |--- COMMON_ORDER end | |
|link:#TXA[TXA] |Document Notification | |9
|[\{CON}] |Consent Segment | |9
|\{ | | |
|link:#OBX[OBX] |Observation/Result (one or more required) | |7
|[ \{ PRT } ] |Participation | |7
|[\{ NTE }] |Notes and comments about the OBX | |2
|} | | |
|===

[width="100%",cols="18%,26%,6%,17%,16%,17%",options="header",]
|===
|Acknowledgement Choreography | | | | |
|MDM^T06^MDM_T02 | | | | |
|Field name |Field Value: Original mode |Field value: Enhanced mode | | |
|MSH-15 |Blank |NE |AL, SU, ER |NE |AL, SU, ER
|MSH-16 |Blank |NE |NE |AL, SU, ER |AL, SU, ER
|Immediate Ack |ACK^T06^ACK |- |ACK^T06^ACK |- |ACK^T06^ACK
|Application Ack |- |- |- |ACK^T06^ACK |ACK^T06^ACK
|===

ACK^T06^ACK: General Acknowledgment

[width="100%",cols="33%,47%,9%,11%",options="header",]
|===
|Segments |Description |Status |Chapter
|MSH |Message Header | |2
|[\{ link:#SFT[SFT] }] |Software Segment | |2
|[ UAC ] |User Authentication Credential | |2
|MSA |Message Acknowledgment | |2
|[\{ link:#ERR[ERR] }] |Error Information | |2
|===

[width="100%",cols="23%,37%,10%,30%",options="header",]
|===
|Acknowledgement Choreography | | |
|ACK^T06^ACK | | |
|Field name |Field Value: Original mode |Field value: Enhanced mode |
|MSH-15 |Blank |NE |AL, SU, ER
|MSH-16 |Blank |NE |NE
|Immediate Ack |ACK^T06^ACK |- |ACK^T06^ACK
|Application Ack |- |- |-
|===

=== 9.6.7 MDM/ACK - Document Edit Notification (Event T07)

*Note:* The only valid use of this trigger event is for documents whose availability status is "Unavailable," i.e., the document has not been made available for patient care.

This is a notification of an edit to a document without the accompanying content.

*Scenario:* Errors, which need to be corrected, are discovered in a document. The original document is edited, and an edit notification is sent.

MDM^T07^MDM_T01: Document Edit Notification

[width="100%",cols="33%,47%,9%,11%",options="header",]
|===
|Segments |Description |Status |Chapter
|MSH |Message Header | |2
|[\{SFT}] |Software Segment | |2
|[ UAC ] |User Authentication Credential | |2
|EVN |Event Type |B, v2.5 |3
|PID |Patient Identification | |3
|[ \{ GSP } ] |Person Gender and Sex | |3
|[ \{ GSR } ] |Recorded Gender and Sex | |3
|[ \{ GSC } ] |Sex Parameter for Clinical Use | |3
|[ \{ PRT } ] |Participation | |7
|PV1 |Patient Visit | |3
|[ \{ PRT } ] |Participation | |7
|[\{ |--- COMMON_ORDER begin | |
|ORC |Common order segment | |4
|[\{ PRT }] |Participation | |7
|[\{ |--- TIMING begin | |
|TQ1 |Timing/Quantity | |4
|[\{TQ2}] |Timing/Quantity Order Sequence | |4
|}] |--- TIMING end | |
|OBR |Observation request segment | |4
|[\{ PRT }] |Participation | |7
|[\{ NTE }] |Notes and comments about the OBR | |2
|}] |--- COMMON_ORDER end | |
|link:#TXA[TXA] |Document Notification | |9
|[\{CON}] |Consent Segment | |9
|===

[width="100%",cols="18%,25%,6%,17%,16%,18%",options="header",]
|===
|Acknowledgement Choreography | | | | |
|MDM^T07^MDM_T01 | | | | |
|Field name |Field Value: Original mode |Field value: Enhanced mode | | |
|MSH-15 |Blank |NE |AL, SU, ER |NE |AL, SU, ER
|MSH-16 |Blank |NE |NE |AL, SU, ER |AL, SU, ER
|Immediate Ack |ACK^T07^ACK |- |ACK^T07^ACK |- |ACK^T07^ACK
|Application Ack |- |- |- |ACK^T07^ACK |ACK^T07^ACK
|===

ACK^T07^ACK: General Acknowledgment

[width="100%",cols="33%,47%,9%,11%",options="header",]
|===
|Segments |Description |Status |Chapter
|MSH |Message Header | |2
|[\{ link:#SFT[SFT] }] |Software Segment | |2
|[ UAC ] |User Authentication Credential | |2
|MSA |Message Acknowledgment | |2
|[\{ link:#ERR[ERR] }] |Error Information | |2
|===

[width="100%",cols="23%,37%,10%,30%",options="header",]
|===
|Acknowledgement Choreography | | |
|ACK^T07^ACK | | |
|Field name |Field Value: Original mode |Field value: Enhanced mode |
|MSH-15 |Blank |NE |AL, SU, ER
|MSH-16 |Blank |NE |NE
|Immediate Ack |ACK^T07^ACK |- |ACK^T07^ACK
|Application Ack |- |- |-
|===

=== 9.6.8 MDM/ACK - Document Edit Notification and Content (Event T08)

*Note:* The only valid use of this trigger event is for documents whose availability status is "Unavailable," i.e., the document has not been made available for patient care.

This is a notification of an edit to a document with the accompanying content.

*Scenario*: Errors, which need to be corrected, are discovered in a document. The original document is edited, and an edit notification and document content are sent.

MDM^T08^MDM_T02: Document Edit Notification & Content

[width="100%",cols="33%,47%,9%,11%",options="header",]
|===
|Segments |Description |Status |Chapter
|MSH |Message Header | |2
|[\{SFT}] |Software Segment | |2
|[ UAC ] |User Authentication Credential | |2
|EVN |Event Type |B, v2.5 |3
|PID |Patient Identification | |3
|[ \{ GSP } ] |Person Gender and Sex | |3
|[ \{ GSR } ] |Recorded Gender and Sex | |3
|[ \{ GSC } ] |Sex Parameter for Clinical Use | |3
|[ \{ PRT } ] |Participation | |7
|PV1 |Patient Visit | |3
|[ \{ PRT } ] |Participation Segment | |7
|[\{ |--- COMMON_ORDER begin | |
|ORC |Common order segment | |4
|[ \{ PRT } ] |Participation | |7
|[\{ |--- TIMING begin | |
|TQ1 |Timing/Quantity | |4
|[\{TQ2}] |Timing/Quantity Order Sequence | |4
|}] |--- TIMING end | |
|OBR |Observation request segment | |4
|[ \{ PRT } ] |Participation | |7
|[\{ NTE }] |Notes and comments about the OBR | |2
|}] |--- COMMON_ORDER end | |
|link:#TXA[TXA] |Document Notification | |9
|[\{CON}] |Consent Segment | |9
|\{ | | |
|link:#OBX[OBX] |Observation/Result (one or more required) | |7
|[ \{ PRT } ] |Participation | |7
|[\{ NTE }] |Notes and comments about the OBX | |2
|} | | |
|===

[width="100%",cols="18%,25%,6%,17%,16%,18%",options="header",]
|===
|Acknowledgement Choreography | | | | |
|MDM^T08^MDM_T02 | | | | |
|Field name |Field Value: Original mode |Field value: Enhanced mode | | |
|MSH-15 |Blank |NE |AL, SU, ER |NE |AL, SU, ER
|MSH-16 |Blank |NE |NE |AL, SU, ER |AL, SU, ER
|Immediate Ack |ACK^T08^ACK |- |ACK^T08^ACK |- |ACK^T08^ACK
|Application Ack |- |- |- |ACK^T08^ACK |ACK^T08^ACK
|===

ACK^T08^ACK: General Acknowledgment

[width="100%",cols="33%,47%,9%,11%",options="header",]
|===
|Segments |Description |Status |Chapter
|MSH |Message Header | |2
|[\{ link:#SFT[SFT] }] |Software Segment | |2
|[ UAC ] |User Authentication Credential | |2
|MSA |Message Acknowledgment | |2
|[\{ link:#ERR[ERR] }] |Error Information | |2
|===

[width="100%",cols="23%,37%,10%,30%",options="header",]
|===
|Acknowledgement Choreography | | |
|ACK^T08^ACK | | |
|Field name |Field Value: Original mode |Field value: Enhanced mode |
|MSH-15 |Blank |NE |AL, SU, ER
|MSH-16 |Blank |NE |NE
|Immediate Ack |ACK^T08^ACK |- |ACK^T08^ACK
|Application Ack |- |- |-
|===

=== 9.6.9 MDM/ACK - Document Replacement Notification (Event T09)

*Note*: This trigger event is generally used when the original document availability status is "Available."

This is a notification of replacement to a document without the accompanying content.

*Scenario*: Errors discovered in a document are corrected. The original document is replaced with the revised document. The replacement document has its own new unique document ID that is linked to the original document via the parent ID. The availability status of the original document is changed to "Obsolete" but the original document should be retained in the system for historical reference. Document replacement notification is sent.

MDM^T09^MDM_T01: Document Replacement Notification

[width="100%",cols="33%,47%,9%,11%",options="header",]
|===
|Segments |Description |Status |Chapter
|MSH |Message Header | |2
|[\{SFT}] |Software Segment | |2
|[ UAC ] |User Authentication Credential | |2
|EVN |Event Type |B, v2.5 |3
|PID |Patient Identification | |3
|[ \{ GSP } ] |Person Gender and Sex | |3
|[ \{ GSR } ] |Recorded Gender and Sex | |3
|[ \{ GSC } ] |Sex Parameter for Clinical Use | |3
|[ \{ PRT } ] |Participation | |7
|PV1 |Patient Visit | |3
|[ \{ PRT } ] |Participation Segment | |7
|[\{ |--- COMMON_ORDER begin | |
|ORC |Common order segment | |4
|[\{ PRT }] |Participation | |7
|[\{ |--- TIMING begin | |
|TQ1 |Timing/Quantity | |4
|[\{TQ2}] |Timing/Quantity Order Sequence | |4
|}] |--- TIMING end | |
|OBR |Observation request segment | |4
|[\{ PRT }] |Participation | |7
|[\{ NTE }] |Notes and comments about the OBR | |2
|}] |--- COMMON_ORDER end | |
|link:#TXA[TXA] |Document Notification | |9
|[\{CON}] |Consent Segment | |9
|===

[width="100%",cols="18%,26%,6%,17%,16%,17%",options="header",]
|===
|Acknowledgement Choreography | | | | |
|MDM^T09^MDM_T01 | | | | |
|Field name |Field Value: Original mode |Field value: Enhanced mode | | |
|MSH-15 |Blank |NE |AL, SU, ER |NE |AL, SU, ER
|MSH-16 |Blank |NE |NE |AL, SU, ER |AL, SU, ER
|Immediate Ack |ACK^T09^ACK |- |ACK^T09^ACK |- |ACK^T09^ACK
|Application Ack |- |- |- |ACK^T09^ACK |ACK^T09^ACK
|===

ACK^T09^ACK: General Acknowledgment

[width="100%",cols="33%,47%,9%,11%",options="header",]
|===
|Segments |Description |Status |Chapter
|MSH |Message Header | |2
|[\{ link:#SFT[SFT] }] |Software Segment | |2
|[ UAC ] |User Authentication Credential | |2
|MSA |Message Acknowledgment | |2
|[\{ link:#ERR[ERR] }] |Error Information | |2
|===

[width="100%",cols="23%,37%,10%,30%",options="header",]
|===
|Acknowledgement Choreography | | |
|ACK^T09^ACK | | |
|Field name |Field Value: Original mode |Field value: Enhanced mode |
|MSH-15 |Blank |NE |AL, SU, ER
|MSH-16 |Blank |NE |NE
|Immediate Ack |ACK^T09^ACK |- |ACK^T09^ACK
|Application Ack |- |- |-
|===

=== 9.6.10 MDM/ACK - Document Replacement Notification and Content (Event T10)

*Scenario:* Errors discovered in a document are corrected. The original document is replaced with the revised document. The replacement document has its own new unique document ID that is linked to the original document via the parent ID. The availability status of the original document is changed to "Obsolete" but the original document should be retained in the system for historical reference. Document replacement notification and document content are sent.

MDM^T10^MDM_T02: Document Replacement Notification & Content

[width="100%",cols="33%,47%,9%,11%",options="header",]
|===
|Segments |Description |Status |Chapter
|MSH |Message Header | |2
|[\{SFT}] |Software Segment | |2
|[ UAC ] |User Authentication Credential | |2
|EVN |Event Type |B, v2.5 |3
|PID |Patient Identification | |3
|[ \{ GSP } ] |Person Gender and Sex | |3
|[ \{ GSR } ] |Recorded Gender and Sex | |3
|[ \{ GSC } ] |Sex Parameter for Clinical Use | |3
|[ \{ PRT } ] |Participation | |7
|PV1 |Patient Visit | |3
|[ \{ PRT } ] |Participation Segment | |7
|[\{ |--- COMMON_ORDER begin | |
|ORC |Common order segment | |4
|[\{ PRT }] |Participation | |7
|[\{ |--- TIMING begin | |
|TQ1 |Timing/Quantity | |4
|[\{TQ2}] |Timing/Quantity Order Sequence | |4
|}] |--- TIMING end | |
|OBR |Observation request segment | |4
|[\{ PRT }] |Participation | |7
|[\{ NTE }] |Notes and comments about the OBR | |2
|}] |--- COMMON_ORDER end | |
|link:#TXA[TXA] |Document Notification | |9
|[\{CON}] |Consent Segment | |9
|\{ | | |
|link:#OBX[OBX] |Observation/Result (one or more required) | |7
|[\{ PRT }] |Participation | |7
|[\{ NTE }] |Notes and comments about the OBX | |2
|} | | |
|===

[width="100%",cols="18%,25%,6%,17%,17%,17%",options="header",]
|===
|Acknowledgement Choreography | | | | |
|MDM^T10^MDM_T02 | | | | |
|Field name |Field Value: Original mode |Field value: Enhanced mode | | |
|MSH-15 |Blank |NE |AL, SU, ER |NE |AL, SU, ER
|MSH-16 |Blank |NE |NE |AL, SU, ER |AL, SU, ER
|Immediate Ack |ACK^T10^ACK |- |ACK^T10^ACK |- |ACK^T10^ACK
|Application Ack |- |- |- |ACK^T10^ACK |ACK^T10^ACK
|===

ACK^T10^ACK: General Acknowledgment

[width="100%",cols="33%,47%,9%,11%",options="header",]
|===
|Segments |Description |Status |Chapter
|MSH |Message Header | |2
|[\{ link:#SFT[SFT] }] |Software Segment | |2
|[ UAC ] |User Authentication Credential | |2
|MSA |Message Acknowledgment | |2
|[\{ link:#ERR[ERR] }] |Error Information | |2
|===

[width="100%",cols="23%,37%,10%,30%",options="header",]
|===
|Acknowledgement Choreography | | |
|ACK^T10^ACK | | |
|Field name |Field Value: Original mode |Field value: Enhanced mode |
|MSH-15 |Blank |NE |AL, SU, ER
|MSH-16 |Blank |NE |NE
|Immediate Ack |ACK^T10^ACK |- |ACK^T10^ACK
|Application Ack |- |- |-
|===

=== 9.6.11 MDM/ACK - Document Cancel Notification (Event T11)

This is a notification of a cancellation of a document. This trigger event should be used only for an original document with an availability status of "Unavailable." When a document has been made available for patient care, the process should be to replace the original document, which then becomes obsolete. The replacement document describes why the erroneous information exists.

*Scenario:* When the author dictated a document, the wrong patient identification was given, and the document was transcribed and sent to the wrong patient's record. When the error is discovered, a cancellation notice is sent to remove the document from general access in the wrong patient's record. In these cases, a reason should be supplied in the cancellation message. To protect patient privacy, the correct patient's identifying information should not be placed on the erroneous document that is retained in the wrong patient's record for historical reference. A new document notification and content will be created using a T02 (original document notification and content) event and sent for association with the correct patient's record.

MDM^T11^MDM_T01: Document Cancel Notification

[width="100%",cols="33%,47%,9%,11%",options="header",]
|===
|Segments |Description |Status |Chapter
|MSH |Message Header | |2
|[\{SFT}] |Software Segment | |2
|[ UAC ] |User Authentication Credential | |2
|EVN |Event Type |B, v2.5 |3
|PID |Patient Identification | |3
|[ \{ GSP } ] |Person Gender and Sex | |3
|[ \{ GSR } ] |Recorded Gender and Sex | |3
|[ \{ GSC } ] |Sex Parameter for Clinical Use | |3
|[ \{ PRT } ] |Participation | |7
|PV1 |Patient Visit | |3
|[ \{ PRT } ] |Participation Segment | |7
|[\{ |--- COMMON_ORDER begin | |
|ORC |Common order segment | |4
|[ \{ PRT } ] |Participation | |7
|[\{ |--- TIMING begin | |4
|TQ1 |Timing/Quantity | |4
|[\{TQ2}] |Timing/Quantity Order Sequence | |4
|}] |--- TIMING end | |
|OBR |Observation request segment | |4
|[ \{ PRT } ] |Participation | |7
|[\{ NTE }] |Notes and comments about the OBR | |2
|}] |--- COMMON_ORDER end | |
|link:#TXA[TXA] |Document Notification | |9
|[\{CON}] |Consent Segment | |9
|===

[width="100%",cols="18%,26%,6%,17%,16%,17%",options="header",]
|===
|Acknowledgement Choreography | | | | |
|MDM^T11^MDM_T01 | | | | |
|Field name |Field Value: Original mode |Field value: Enhanced mode | | |
|MSH-15 |Blank |NE |AL, SU, ER |NE |AL, SU, ER
|MSH-16 |Blank |NE |NE |AL, SU, ER |AL, SU, ER
|Immediate Ack |ACK^T11^ACK |- |ACK^T11^ACK |- |ACK^T11^ACK
|Application Ack |- |- |- |ACK^T11^ACK |ACK^T11^ACK
|===

ACK^T11^ACK: General Acknowledgment

[width="100%",cols="33%,47%,9%,11%",options="header",]
|===
|Segments |Description |Status |Chapter
|MSH |Message Header | |2
|[\{ link:#SFT[SFT] }] |Software segment | |2
|[ UAC ] |User Authentication Credential | |2
|MSA |Message Acknowledgment | |2
|[\{ link:#ERR[ERR] }] |Error Information | |2
|===

[width="100%",cols="23%,37%,10%,30%",options="header",]
|===
|Acknowledgement Choreography | | |
|ACK^T11^ACK | | |
|Field name |Field Value: Original mode |Field value: Enhanced mode |
|MSH-15 |Blank |NE |AL, SU, ER
|MSH-16 |Blank |NE |NE
|Immediate Ack |ACK^T11^ACK |- |ACK^T11^ACK
|Application Ack |- |- |-
|===

== 9.7 MESSAGE SEGMENTS

=== 9.7.1 CON – Consent Segment

This segment identifies patient consent information relating to a particular message. It can be used as part of existing messages to convey information about patient consent to procedures, admissions, information release/exchange or other events discussed by the message. It may also be used in messages focusing on recording or requesting consent and for consents related to employees or service providers.

The segment will be used in conjunction with various other segments to identify the practitioner (PRA/STF) or patient (PID) the consent is for, the various individuals involved in the consent (ROL) as witnesses, consenting person (not always the patient), translators, consulting providers, etc., and the specific procedures being proposed (PR1).

HL7 Attribute Table – CON –Consent Segment

[width="100%",cols="14%,6%,7%,6%,6%,6%,7%,7%,41%",options="header",]
|===
|SEQ |LEN |C.LEN |DT |OPT |RP/# |TBL# |ITEM# |ELEMENT NAME
|1 |1..4 | |SI |R | | |01776 |Set ID - CON
|2 | | |CWE |O | |file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70496[0496] |01777 |Consent Type
|3 | | |ST |O | | |01778 |Consent Form ID and Version
|4 | | |EI |O | | |01779 |Consent Form Number
|5 | | |FT |O |Y | |01780 |Consent Text
|6 | | |FT |O |Y | |01781 |Subject-specific Consent Text
|7 | | |FT |O |Y | |01782 |Consent Background Information
|8 | | |FT |O |Y | |01783 |Subject-specific Consent Background Text
|9 | | |FT |O |Y | |01784 |Consenter-imposed limitations
|10 | | |CNE |O | |file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70497[0497] |01785 |Consent Mode
|11 | | |CNE |R | |file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70498[0498] |01786 |Consent Status
|12 | | |DTM |O | | |01787 |Consent Discussion Date/Time
|13 | | |DTM |O | | |01788 |Consent Decision Date/Time
|14 | | |DTM |O | | |01789 |Consent Effective Date/Time
|15 | | |DTM |O | | |01790 |Consent End Date/Time
|16 |1..1 | |ID |O | |file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70136[0136] |01791 |Subject Competence Indicator
|17 |1..1 | |ID |O | |file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70136[0136] |01792 |Translator Assistance Indicator
|18 | | |CWE |O | |file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70296[0296] |01793 |Language Translated To
|19 |1..1 | |ID |O | |file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70136[0136] |01794 |Informational Material Supplied Indicator
|20 | | |CWE |O | |file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70499[0499] |01795 |Consent Bypass Reason
|21 |1..1 | |ID |O | |file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70500[0500] |01796 |Consent Disclosure Level
|22 | | |CWE |O | |file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70501[0501] |01797 |Consent Non-disclosure Reason
|23 | | |CWE |O | |file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70502[0502] |01798 |Non-subject Consenter Reason
|24 | | |XPN |R |Y | |01909 |Consenter ID
|25 | | |CWE |R |Y |file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70548[0548] |01898 |Relationship to Subject
|===

==== 9.7.1.0 CON Segment Field Definitions

==== 9.7.1.1 CON-1 Set ID -CON (SI) 01776

Definition: This field contains the number that identifies this segment instance within the message. For the first occurrence of the segment, the sequence number shall be one; for the second occurrence, the sequence number shall be two; etc.

==== 9.7.1.2 CON-2 Consent Type (CWE) 01777

Components: <Identifier (ST)> ^ <Text (ST)> ^ <Name of Coding System (ID)> ^ <Alternate Identifier (ST)> ^ <Alternate Text (ST)> ^ <Name of Alternate Coding System (ID)> ^ <Coding System Version ID (ST)> ^ <Alternate Coding System Version ID (ST)> ^ <Original Text (ST)> ^ <Second Alternate Identifier (ST)> ^ <Second Alternate Text (ST)> ^ <Name of Second Alternate Coding System (ID)> ^ <Second Alternate Coding System Version ID (ST)> ^ <Coding System OID (ST)> ^ <Value Set OID (ST)> ^ <Value Set Version ID (DTM)> ^ <Alternate Coding System OID (ST)> ^ <Alternate Value Set OID (ST)> ^ <Alternate Value Set Version ID (DTM)> ^ <Second Alternate Coding System OID (ST)> ^ <Second Alternate Value Set OID (ST)> ^ <Second Alternate Value Set Version ID (DTM)>

Definition: This field describes what the subject is consenting to, i.e., what type of service, surgical procedure, information access/release or other event. For values see file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70496[_User-Defined Table 0496 – Consent Type._]

==== 9.7.1.3 CON-3 Consent Form ID and Version (ST) 01778

Definition: Identifies a specific version of a consent form used to record the consent. A given version of a consent form implies a particular set of wording that appears on the form.

==== 9.7.1.4 CON-4 Consent Form Number (EI) 01779

Components: <Entity Identifier (ST)> ^ <Namespace ID (IS)> ^ <Universal ID (ST)> ^ <Universal ID Type (ID)>

Definition: Uniquely identifies a specific recorded consent. This may be the number assigned to an electronic consent, or may be the number on a printed consent form.

==== 9.7.1.5 CON-5 Consent Text (FT) 01780

Definition: Describes the specific procedures/information releases/events the subject is consenting to.

==== 9.7.1.6 CON-6 Subject-specific Consent Text (FT) 01781

Definition: Describes any additions or variations to the standard procedures/information releases/events from a standard consent that are applicable to the subject whose consent is sought.

==== 9.7.1.7 CON-7 Consent Background Information (FT) 01782

Definition: Describes any additional information relating to the procedure/information release/event that needs to be understood by the subject for informed consent. May include the reason for the service, the expected benefit, risks, etc.

==== 9.7.1.8 CON-8 Subject-specific Consent Background Text (FT) 01783

Definition: Describes any additions or variations to the standard additional information that needs to be understood by the patient for informed consent. May include a description of benefits and risks that are specific to the subject from whom consent is sought. May also include an indication that there are *no* subject-specific risks/benefits.

==== 9.7.1.9 CON-9 Consenter-imposed Limitations (FT) 01784

Definition: Describes any restrictions or limitations placed on their consent by the subject.

==== 9.7.1.10 CON-10 Consent Mode (CNE) 01785

Components: <Identifier (ST)> ^ <Text (ST)> ^ <Name of Coding System (ID)> ^ <Alternate Identifier (ST)> ^ <Alternate Text (ST)> ^ <Name of Alternate Coding System (ID)> ^ <Coding System Version ID (ST)> ^ <Alternate Coding System Version ID (ST)> ^ <Original Text (ST)> ^ <Second Alternate Identifier (ST)> ^ <Second Alternate Text (ST)> ^ <Name of Second Alternate Coding System (ID)> ^ <Second Alternate Coding System Version ID (ST)> ^ <Coding System OID (ST)> ^ <Value Set OID (ST)> ^ <Value Set Version ID (DTM)> ^ <Alternate Coding System OID (ST)> ^ <Alternate Value Set OID (ST)> ^ <Alternate Value Set Version ID (DTM)> ^ <Second Alternate Coding System OID (ST)> ^ <Second Alternate Value Set OID (ST)> ^ <Second Alternate Value Set Version ID (DTM)>

Definition: The method in which a subject provides consent. For values see file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70497[_HL7 Table 0497 – Consent Mode._]

==== 9.7.1.11 CON-11 Consent Status (CNE) 01786

Components: <Identifier (ST)> ^ <Text (ST)> ^ <Name of Coding System (ID)> ^ <Alternate Identifier (ST)> ^ <Alternate Text (ST)> ^ <Name of Alternate Coding System (ID)> ^ <Coding System Version ID (ST)> ^ <Alternate Coding System Version ID (ST)> ^ <Original Text (ST)> ^ <Second Alternate Identifier (ST)> ^ <Second Alternate Text (ST)> ^ <Name of Second Alternate Coding System (ID)> ^ <Second Alternate Coding System Version ID (ST)> ^ <Coding System OID (ST)> ^ <Value Set OID (ST)> ^ <Value Set Version ID (DTM)> ^ <Alternate Coding System OID (ST)> ^ <Alternate Value Set OID (ST)> ^ <Alternate Value Set Version ID (DTM)> ^ <Second Alternate Coding System OID (ST)> ^ <Second Alternate Value Set OID (ST)> ^ <Second Alternate Value Set Version ID (DTM)>

Definition: Indicates whether consent has been sought and granted. For values see file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70498[_HL7 Table 0498 – Consent Status_].

==== 9.7.1.12 CON-12 Consent Discussion Date/Time (DTM) 01787

Definition: Identifies the time when consent was discussed with the subject. This should only be specified if this differs from the time the consent decision is made.

==== 9.7.1.13 CON-13 Consent Decision Date/Time (DTM) 01788

Definition: Identifies the time when the decision to grant/refuse consent was made. In the case of written consent, this is the time the consent form is signed.

==== 9.7.1.14 CON-14 Consent Effective Date/Time (DTM) 01789

Definition: The time the consent becomes/became effective. This only needs to be specified if the time differs from the Consent Decision Date/Time

==== 9.7.1.15 CON-15 Consent End Date/Time (DTM) 01790

Definition: The time the consent becomes ineffective. If not specified, the consent is assumed to be indefinite. For consents relating to information release, the end date/time is the date by which the released information must be returned/destroyed.

==== 9.7.1.16 CON-16 Subject Competence Indicator (ID) 01791

Definition: Identifies whether the subject was deemed competent to provide consent. Refer to table file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70136[_HL7 Table 0136 – Yes/No Indicator._]

==== 9.7.1.17 CON-17 Translator Assistance Indicator (ID) 01792

Definition: Identifies whether translation was (or will be) required to obtain informed consent from the subject. Refer to table file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70136[_HL7 Table 0136 – Yes/No Indicator._]

==== 9.7.1.18 CON-18 Language Translated To (CWE) 01793

Components: <Identifier (ST)> ^ <Text (ST)> ^ <Name of Coding System (ID)> ^ <Alternate Identifier (ST)> ^ <Alternate Text (ST)> ^ <Name of Alternate Coding System (ID)> ^ <Coding System Version ID (ST)> ^ <Alternate Coding System Version ID (ST)> ^ <Original Text (ST)> ^ <Second Alternate Identifier (ST)> ^ <Second Alternate Text (ST)> ^ <Name of Second Alternate Coding System (ID)> ^ <Second Alternate Coding System Version ID (ST)> ^ <Coding System OID (ST)> ^ <Value Set OID (ST)> ^ <Value Set Version ID (DTM)> ^ <Alternate Coding System OID (ST)> ^ <Alternate Value Set OID (ST)> ^ <Alternate Value Set Version ID (DTM)> ^ <Second Alternate Coding System OID (ST)> ^ <Second Alternate Value Set OID (ST)> ^ <Second Alternate Value Set Version ID (DTM)>

Definition: Identifies the language the consent material must be translated to. Refer to _file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70296[User Defined table 0296 – Primary Language]_ which contains no suggested values. This table may be populated with values similar to those that may be found in _ISO table 639 – Language Codes._

==== 9.7.1.19 CON-19 Informational Material Supplied Indicator (ID) 01794

Definition: Identifies whether additional educational or reference material was provided to the subject as part of the consent process. Refer to table file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70136[_HL7 Table 0136 – Yes/No Indicator._]

==== 9.7.1.20 CON-20 Consent Bypass Reason (CWE) 01795

Components: <Identifier (ST)> ^ <Text (ST)> ^ <Name of Coding System (ID)> ^ <Alternate Identifier (ST)> ^ <Alternate Text (ST)> ^ <Name of Alternate Coding System (ID)> ^ <Coding System Version ID (ST)> ^ <Alternate Coding System Version ID (ST)> ^ <Original Text (ST)> ^ <Second Alternate Identifier (ST)> ^ <Second Alternate Text (ST)> ^ <Name of Second Alternate Coding System (ID)> ^ <Second Alternate Coding System Version ID (ST)> ^ <Coding System OID (ST)> ^ <Value Set OID (ST)> ^ <Value Set Version ID (DTM)> ^ <Alternate Coding System OID (ST)> ^ <Alternate Value Set OID (ST)> ^ <Alternate Value Set Version ID (DTM)> ^ <Second Alternate Coding System OID (ST)> ^ <Second Alternate Value Set OID (ST)> ^ <Second Alternate Value Set Version ID (DTM)>

Definition: Identifies why the subject's consent was not sought. This field must be populated when _CON-11 - Consent Status_ is B – Bypassed. Refer to file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70499[_User Defined table 0499 – Consent Bypass Reason_] for suggested values.

==== 9.7.1.21 CON-21 Consent Disclosure Level (ID) 01796

Definition: Identifies how much information was disclosed to the subject as part of the informed consent process. Refer to table file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70500[_HL7 Table 0500 – Consent Disclosure Level_].

==== 9.7.1.22 CON-22 Consent Non-Disclosure Reason (CWE) 01797

Components: <Identifier (ST)> ^ <Text (ST)> ^ <Name of Coding System (ID)> ^ <Alternate Identifier (ST)> ^ <Alternate Text (ST)> ^ <Name of Alternate Coding System (ID)> ^ <Coding System Version ID (ST)> ^ <Alternate Coding System Version ID (ST)> ^ <Original Text (ST)> ^ <Second Alternate Identifier (ST)> ^ <Second Alternate Text (ST)> ^ <Name of Second Alternate Coding System (ID)> ^ <Second Alternate Coding System Version ID (ST)> ^ <Coding System OID (ST)> ^ <Value Set OID (ST)> ^ <Value Set Version ID (DTM)> ^ <Alternate Coding System OID (ST)> ^ <Alternate Value Set OID (ST)> ^ <Alternate Value Set Version ID (DTM)> ^ <Second Alternate Coding System OID (ST)> ^ <Second Alternate Value Set OID (ST)> ^ <Second Alternate Value Set Version ID (DTM)>

Definition: Identifies why the subject did not receive full disclosure. . Refer to file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70501[_User-Defined Table 0501 – Consent Non-Disclosure Reason_] for suggested values.

==== 9.7.1.23 CON-23 Non-Subject Consenter Reason (CWE) 01798

Components: <Identifier (ST)> ^ <Text (ST)> ^ <Name of Coding System (ID)> ^ <Alternate Identifier (ST)> ^ <Alternate Text (ST)> ^ <Name of Alternate Coding System (ID)> ^ <Coding System Version ID (ST)> ^ <Alternate Coding System Version ID (ST)> ^ <Original Text (ST)> ^ <Second Alternate Identifier (ST)> ^ <Second Alternate Text (ST)> ^ <Name of Second Alternate Coding System (ID)> ^ <Second Alternate Coding System Version ID (ST)> ^ <Coding System OID (ST)> ^ <Value Set OID (ST)> ^ <Value Set Version ID (DTM)> ^ <Alternate Coding System OID (ST)> ^ <Alternate Value Set OID (ST)> ^ <Alternate Value Set Version ID (DTM)> ^ <Second Alternate Coding System OID (ST)> ^ <Second Alternate Value Set OID (ST)> ^ <Second Alternate Value Set Version ID (DTM)>

Definition: Identifies why consent was granted by a person other than the subject of the consent. Refer to file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70502[_User-defined Table 0502 – Non-Subject Consenter Reason_] for suggested values.

==== 9.7.1.24 CON-24 Consenter ID (XPN) 01909

Components: <Family Name (FN)> ^ <Given Name (ST)> ^ <Second and Further Given Names or Initials Thereof (ST)> ^ <Suffix (e.g., JR or III) (ST)> ^ <Prefix (e.g., DR) (ST)> ^ <WITHDRAWN Constituent> ^ <Name Type Code (ID)> ^ <Name Representation Code (ID)> ^ <Name Context (CWE)> ^ <WITHDRAWN Constituent> ^ <Name Assembly Order (ID)> ^ <Effective Date (DTM)> ^ <Expiration Date (DTM)> ^ <Professional Suffix (ST)> ^ <Called By (ST)>

Subcomponents for Family Name (FN): <Surname (ST)> & <Own Surname Prefix (ST)> & <Own Surname (ST)> & <Surname Prefix from Partner/Spouse (ST)> & <Surname from Partner/Spouse (ST)>

Subcomponents for Name Context (CWE): <Identifier (ST)> & <Text (ST)> & <Name of Coding System (ID)> & <Alternate Identifier (ST)> & <Alternate Text (ST)> & <Name of Alternate Coding System (ID)> & <Coding System Version ID (ST)> & <Alternate Coding System Version ID (ST)> & <Original Text (ST)> & <Second Alternate Identifier (ST)> & <Second Alternate Text (ST)> & <Name of Second Alternate Coding System (ID)> & <Second Alternate Coding System Version ID (ST)> & <Coding System OID (ST)> & <Value Set OID (ST)> & <Value Set Version ID (DTM)> & <Alternate Coding System OID (ST)> & <Alternate Value Set OID (ST)> & <Alternate Value Set Version ID (DTM)> & <Second Alternate Coding System OID (ST)> & <Second Alternate Value Set OID (ST)> & <Second Alternate Value Set Version ID (DTM)>

Definition: Identification of the individual(s) who is (are) consenting.

==== 9.7.1.25 CON-25 Relationship to Subject (CWE) 01898

Components: <Identifier (ST)> ^ <Text (ST)> ^ <Name of Coding System (ID)> ^ <Alternate Identifier (ST)> ^ <Alternate Text (ST)> ^ <Name of Alternate Coding System (ID)> ^ <Coding System Version ID (ST)> ^ <Alternate Coding System Version ID (ST)> ^ <Original Text (ST)> ^ <Second Alternate Identifier (ST)> ^ <Second Alternate Text (ST)> ^ <Name of Second Alternate Coding System (ID)> ^ <Second Alternate Coding System Version ID (ST)> ^ <Coding System OID (ST)> ^ <Value Set OID (ST)> ^ <Value Set Version ID (DTM)> ^ <Alternate Coding System OID (ST)> ^ <Alternate Value Set OID (ST)> ^ <Alternate Value Set Version ID (DTM)> ^ <Second Alternate Coding System OID (ST)> ^ <Second Alternate Value Set OID (ST)> ^ <Second Alternate Value Set Version ID (DTM)>

Definition: Identification of the relationship of the consenter to the subject. Receivers are required to inspect the Coding System component of the CWE data type to accurately interpret the meaning of the code. Senders transmitting messages to Receivers on earlier version of the standard may elect to negotiate business rules to ensure that expected data is not lost. HL7 does not assign positional meaning to user-defined codes. Refer to file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70548[_User-Defined Table 0548 – Signatory's Relationship to Subject_] for suggested values.

=== 9.7.2 OBX - Observation Segment Usage

The OBX segment is documented in its entirety in Chapter 7. Its usage as it applies to Medical Records/ Information Management is documented here for clarity.

____
*NOTE: The attribute table definition for the OBX Segment has been removed as of 2.8. The reader is directed to the Chapter 7.*.
____

Specialized usage: Observation Identifier/Observation Sub-ID have been used as optional fields that are not required in unstructured text where the nature of the document has been identified in _TXA-2-Document type_, which is a required field, but is expressly allowed in the richer structured documentation. An example includes cases where anatomic reports may have separate OBXs for gross examination, microscopic examination, clinical impression, and final diagnosis. Another possible use includes imbedding non-textual observations within textual reports.

=== 9.7.3 TXA - Transcription Document Header Segment

The TXA segment contains information specific to a transcribed document but does not include the text of the document. The message is created as a result of a document status change. This information updates other healthcare systems and allows them to identify reports that are available in the transcription system. By maintaining the TXA message information in these systems, the information is available when constructing queries to the transcription system requesting the full document text.

HL7 Attribute Table – TXA[#TXA .anchor]#### – Transcription Document Header

[width="100%",cols="14%,6%,7%,6%,6%,6%,7%,7%,41%",options="header",]
|===
|SEQ |LEN |C.LEN |DT |OPT |RP/# |TBL# |ITEM# |ELEMENT NAME
|1 |1..4 | |SI |R | | |00914 |Set ID- TXA
|2 | | |CWE |R | |file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70270[0270] |00915 |Document Type
|3 | | |ID |C | |file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70191[0191] |00916 |Document Content Presentation
|4 | | |DTM |O | | |00917 |Activity Date/Time
|5 | | |XCN |C |Y | |00918 |Primary Activity Provider Code/Name
|6 | | |DTM |O | | |00919 |Origination Date/Time
|7 | | |DTM |C | | |00920 |Transcription Date/Time
|8 | | |DTM |O |Y | |00921 |Edit Date/Time
|9 | | |XCN |O |Y | |00922 |Originator Code/Name
|10 | | |XCN |O |Y | |00923 |Assigned Document Authenticator
|11 | | |XCN |C |Y | |00924 |Transcriptionist Code/Name
|12 | | |EI |R | | |00925 |Unique Document Number
|13 | | |EI |C | | |00926 |Parent Document Number
|14 | | |EI |O |Y | |00216 |Placer Order Number
|15 | | |EI |O | | |00217 |Filler Order Number
|16 | | |ST |O | | |00927 |Unique Document File Name
|17 |2..2 | |ID |R | |file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70271[0271] |00928 |Document Completion Status
|18 |1..1 | |ID |O | |file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70272[0272] |00929 |Document Confidentiality Status
|19 |2..2 | |ID |O | |file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70273[0273] |00930 |Document Availability Status
|20 |2..2 | |ID |O | |file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70275[0275] |00932 |Document Storage Status
|21 | | |ST |O | | |00933 |Document Change Reason
|22 | | |PPN |C |Y | |00934 |Authentication Person, Time Stamp (set)
|23 | | |XCN |O |Y | |00935 |Distributed Copies (Code and Name of Recipient(s) )
|24 | | |CWE |O |Y |0791 |02378 |Folder Assignment
|25 | | |ST |O |Y | |03301 |Document Title
|26 | | |DTM |O | | |03302 |Agreed Due Date/Time
|27 | | |HD |O | | |02413 |Creating Facility
|28 | | |CWE |O | |0792 |02414 |Creating Specialty
|29 | | |CWE |O |Y |0832 |02530 |Document Class
|30 | | |CWE |O |Y |0833 |02531 |Document Event
|31 | | |EI |O |Y | |02532 |Folder Instance Association
|===

==== 9.7.3.0 TXA Field Definitions

==== 9.7.3.1 TXA-1 Set ID - TXA (SI) 00914

Definition: This field contains a number that uniquely identifies this transaction for the purpose of adding, changing, or deleting the transaction.

==== 9.7.3.2 TXA-2 Document Type (CWE) 00915

Components: <Identifier (ST)> ^ <Text (ST)> ^ <Name of Coding System (ID)> ^ <Alternate Identifier (ST)> ^ <Alternate Text (ST)> ^ <Name of Alternate Coding System (ID)> ^ <Coding System Version ID (ST)> ^ <Alternate Coding System Version ID (ST)> ^ <Original Text (ST)> ^ <Second Alternate Identifier (ST)> ^ <Second Alternate Text (ST)> ^ <Name of Second Alternate Coding System (ID)> ^ <Second Alternate Coding System Version ID (ST)> ^ <Coding System OID (ST)> ^ <Value Set OID (ST)> ^ <Value Set Version ID (DTM)> ^ <Alternate Coding System OID (ST)> ^ <Alternate Value Set OID (ST)> ^ <Alternate Value Set Version ID (DTM)> ^ <Second Alternate Coding System OID (ST)> ^ <Second Alternate Value Set OID (ST)> ^ <Second Alternate Value Set Version ID (DTM)>

Definition: This field identifies the type of document (as defined in the transcription system). Refer to file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70270[_User-Defined Table 0270 - Document Type_] for suggested values. The organization is free to add more entries. Receivers are required to inspect the Coding System component of the CWE data type to accurately interpret the meaning of the code. Senders transmitting messages to Receivers on earlier version of the standard may elect to negotiate business rules to ensure that expected data is not lost. HL7 does not assign positional meaning to user-defined codes.

==== 9.7.3.3 TXA-3 Document Content Presentation (ID) 00916

Definition: This is a conditional field which is required whenever the message contains content as presented in one or more OBX segments. This field identifies the method by which this document was obtained or originated. Refer to E:\\V2\\v2.9 final Nov from Frank\\V29_CH02C_Tables.docx#HL70191[_HL7 Table 0191 – Type of Referenced Dat__a_] for valid values.

==== 9.7.3.4 TXA-4 Activity Date/Time (DTM) 00917

Definition: This field contains the date/time identified in the document as the date a procedure or activity was performed. This date can identify date of surgery, non-invasive procedure, consultation, examination, etc.

==== 9.7.3.5 TXA-5 Primary Activity Provider Code/Name (XCN) 00918

Components: <Person Identifier (ST)> ^ <Family Name (FN)> ^ <Given Name (ST)> ^ <Second and Further Given Names or Initials Thereof (ST)> ^ <Suffix (e.g., JR or III) (ST)> ^ <Prefix (e.g., DR) (ST)> ^ <WITHDRAWN Constituent> ^ <DEPRECATED-Source Table (CWE)> ^ <Assigning Authority (HD)> ^ <Name Type Code (ID)> ^ <Identifier Check Digit (ST)> ^ <Check Digit Scheme (ID)> ^ <Identifier Type Code (ID)> ^ <Assigning Facility (HD)> ^ <Name Representation Code (ID)> ^ <Name Context (CWE)> ^ <WITHDRAWN Constituent> ^ <Name Assembly Order (ID)> ^ <Effective Date (DTM)> ^ <Expiration Date (DTM)> ^ <Professional Suffix (ST)> ^ <Assigning Jurisdiction (CWE)> ^ <Assigning Agency or Department (CWE)> ^ <Security Check (ST)> ^ <Security Check Scheme (ID)>

Subcomponents for Family Name (FN): <Surname (ST)> & <Own Surname Prefix (ST)> & <Own Surname (ST)> & <Surname Prefix from Partner/Spouse (ST)> & <Surname from Partner/Spouse (ST)>

Subcomponents for Source Table (CWE): <Identifier (ST)> & <Text (ST)> & <Name of Coding System (ID)> & <Alternate Identifier (ST)> & <Alternate Text (ST)> & <Name of Alternate Coding System (ID)> & <Coding System Version ID (ST)> & <Alternate Coding System Version ID (ST)> & <Original Text (ST)> & <Second Alternate Identifier (ST)> & <Second Alternate Text (ST)> & <Name of Second Alternate Coding System (ID)> & <Second Alternate Coding System Version ID (ST)> & <Coding System OID (ST)> & <Value Set OID (ST)> & <Value Set Version ID (DTM)> & <Alternate Coding System OID (ST)> & <Alternate Value Set OID (ST)> & <Alternate Value Set Version ID (DTM)> & <Second Alternate Coding System OID (ST)> & <Second Alternate Value Set OID (ST)> & <Second Alternate Value Set Version ID (DTM)>

Subcomponents for Assigning Authority (HD): <Namespace ID (IS)> & <Universal ID (ST)> & <Universal ID Type (ID)>

Subcomponents for Assigning Facility (HD): <Namespace ID (IS)> & <Universal ID (ST)> & <Universal ID Type (ID)>

Subcomponents for Name Context (CWE): <Identifier (ST)> & <Text (ST)> & <Name of Coding System (ID)> & <Alternate Identifier (ST)> & <Alternate Text (ST)> & <Name of Alternate Coding System (ID)> & <Coding System Version ID (ST)> & <Alternate Coding System Version ID (ST)> & <Original Text (ST)> & <Second Alternate Identifier (ST)> & <Second Alternate Text (ST)> & <Name of Second Alternate Coding System (ID)> & <Second Alternate Coding System Version ID (ST)> & <Coding System OID (ST)> & <Value Set OID (ST)> & <Value Set Version ID (DTM)> & <Alternate Coding System OID (ST)> & <Alternate Value Set OID (ST)> & <Alternate Value Set Version ID (DTM)> & <Second Alternate Coding System OID (ST)> & <Second Alternate Value Set OID (ST)> & <Second Alternate Value Set Version ID (DTM)>

Subcomponents for Assigning Jurisdiction (CWE): <Identifier (ST)> & <Text (ST)> & <Name of Coding System (ID)> & <Alternate Identifier (ST)> & <Alternate Text (ST)> & <Name of Alternate Coding System (ID)> & <Coding System Version ID (ST)> & <Alternate Coding System Version ID (ST)> & <Original Text (ST)> & <Second Alternate Identifier (ST)> & <Second Alternate Text (ST)> & <Name of Second Alternate Coding System (ID)> & <Second Alternate Coding System Version ID (ST)> & <Coding System OID (ST)> & <Value Set OID (ST)> & <Value Set Version ID (DTM)> & <Alternate Coding System OID (ST)> & <Alternate Value Set OID (ST)> & <Alternate Value Set Version ID (DTM)> & <Second Alternate Coding System OID (ST)> & <Second Alternate Value Set OID (ST)> & <Second Alternate Value Set Version ID (DTM)>

Subcomponents for Assigning Agency or Department (CWE): <Identifier (ST)> & <Text (ST)> & <Name of Coding System (ID)> & <Alternate Identifier (ST)> & <Alternate Text (ST)> & <Name of Alternate Coding System (ID)> & <Coding System Version ID (ST)> & <Alternate Coding System Version ID (ST)> & <Original Text (ST)> & <Second Alternate Identifier (ST)> & <Second Alternate Text (ST)> & <Name of Second Alternate Coding System (ID)> & <Second Alternate Coding System Version ID (ST)> & <Coding System OID (ST)> & <Value Set OID (ST)> & <Value Set Version ID (DTM)> & <Alternate Coding System OID (ST)> & <Alternate Value Set OID (ST)> & <Alternate Value Set Version ID (DTM)> & <Second Alternate Coding System OID (ST)> & <Second Alternate Value Set OID (ST)> & <Second Alternate Value Set Version ID (DTM)>

Definition: This field contains the name of the person identified in the document as being responsible for performing the procedure or activity. This field includes the code and name (if available) of the caregiver. This field is conditional based upon the presence of a value in link:#txa-4-activity-datetime-dtm-00917[TXA-4-Activity Date/Time].

==== 9.7.3.6 TXA-6 Origination Date/Time (DTM) 00919

Definition: This field contains the date and time the document was created (i.e., dictated, recorded, etc.).

==== 9.7.3.7 TXA-7 Transcription Date/Time (DTM) 00920

Definition: This field contains the date and time the input was actually transcribed. This field is conditional based upon the presence of a value in link:#txa-17-document-completion-status-id-00928[TXA-17-Document Completion Status] of anything except "dictated."

==== 9.7.3.8 TXA-8 Edit Date/Time (DTM) 00921

Definition: This field contains the date and time the document was edited.

==== 9.7.3.9 TXA-9 Originator Code/Name (XCN) 00922

Components: <Person Identifier (ST)> ^ <Family Name (FN)> ^ <Given Name (ST)> ^ <Second and Further Given Names or Initials Thereof (ST)> ^ <Suffix (e.g., JR or III) (ST)> ^ <Prefix (e.g., DR) (ST)> ^ <WITHDRAWN Constituent> ^ <DEPRECATED-Source Table (CWE)> ^ <Assigning Authority (HD)> ^ <Name Type Code (ID)> ^ <Identifier Check Digit (ST)> ^ <Check Digit Scheme (ID)> ^ <Identifier Type Code (ID)> ^ <Assigning Facility (HD)> ^ <Name Representation Code (ID)> ^ <Name Context (CWE)> ^ <WITHDRAWN Constituent> ^ <Name Assembly Order (ID)> ^ <Effective Date (DTM)> ^ <Expiration Date (DTM)> ^ <Professional Suffix (ST)> ^ <Assigning Jurisdiction (CWE)> ^ <Assigning Agency or Department (CWE)> ^ <Security Check (ST)> ^ <Security Check Scheme (ID)>

Subcomponents for Family Name (FN): <Surname (ST)> & <Own Surname Prefix (ST)> & <Own Surname (ST)> & <Surname Prefix from Partner/Spouse (ST)> & <Surname from Partner/Spouse (ST)>

Subcomponents for Source Table (CWE): <Identifier (ST)> & <Text (ST)> & <Name of Coding System (ID)> & <Alternate Identifier (ST)> & <Alternate Text (ST)> & <Name of Alternate Coding System (ID)> & <Coding System Version ID (ST)> & <Alternate Coding System Version ID (ST)> & <Original Text (ST)> & <Second Alternate Identifier (ST)> & <Second Alternate Text (ST)> & <Name of Second Alternate Coding System (ID)> & <Second Alternate Coding System Version ID (ST)> & <Coding System OID (ST)> & <Value Set OID (ST)> & <Value Set Version ID (DTM)> & <Alternate Coding System OID (ST)> & <Alternate Value Set OID (ST)> & <Alternate Value Set Version ID (DTM)> & <Second Alternate Coding System OID (ST)> & <Second Alternate Value Set OID (ST)> & <Second Alternate Value Set Version ID (DTM)>

Subcomponents for Assigning Authority (HD): <Namespace ID (IS)> & <Universal ID (ST)> & <Universal ID Type (ID)>

Subcomponents for Assigning Facility (HD): <Namespace ID (IS)> & <Universal ID (ST)> & <Universal ID Type (ID)>

Subcomponents for Name Context (CWE): <Identifier (ST)> & <Text (ST)> & <Name of Coding System (ID)> & <Alternate Identifier (ST)> & <Alternate Text (ST)> & <Name of Alternate Coding System (ID)> & <Coding System Version ID (ST)> & <Alternate Coding System Version ID (ST)> & <Original Text (ST)> & <Second Alternate Identifier (ST)> & <Second Alternate Text (ST)> & <Name of Second Alternate Coding System (ID)> & <Second Alternate Coding System Version ID (ST)> & <Coding System OID (ST)> & <Value Set OID (ST)> & <Value Set Version ID (DTM)> & <Alternate Coding System OID (ST)> & <Alternate Value Set OID (ST)> & <Alternate Value Set Version ID (DTM)> & <Second Alternate Coding System OID (ST)> & <Second Alternate Value Set OID (ST)> & <Second Alternate Value Set Version ID (DTM)>

Subcomponents for Assigning Jurisdiction (CWE): <Identifier (ST)> & <Text (ST)> & <Name of Coding System (ID)> & <Alternate Identifier (ST)> & <Alternate Text (ST)> & <Name of Alternate Coding System (ID)> & <Coding System Version ID (ST)> & <Alternate Coding System Version ID (ST)> & <Original Text (ST)> & <Second Alternate Identifier (ST)> & <Second Alternate Text (ST)> & <Name of Second Alternate Coding System (ID)> & <Second Alternate Coding System Version ID (ST)> & <Coding System OID (ST)> & <Value Set OID (ST)> & <Value Set Version ID (DTM)> & <Alternate Coding System OID (ST)> & <Alternate Value Set OID (ST)> & <Alternate Value Set Version ID (DTM)> & <Second Alternate Coding System OID (ST)> & <Second Alternate Value Set OID (ST)> & <Second Alternate Value Set Version ID (DTM)>

Subcomponents for Assigning Agency or Department (CWE): <Identifier (ST)> & <Text (ST)> & <Name of Coding System (ID)> & <Alternate Identifier (ST)> & <Alternate Text (ST)> & <Name of Alternate Coding System (ID)> & <Coding System Version ID (ST)> & <Alternate Coding System Version ID (ST)> & <Original Text (ST)> & <Second Alternate Identifier (ST)> & <Second Alternate Text (ST)> & <Name of Second Alternate Coding System (ID)> & <Second Alternate Coding System Version ID (ST)> & <Coding System OID (ST)> & <Value Set OID (ST)> & <Value Set Version ID (DTM)> & <Alternate Coding System OID (ST)> & <Alternate Value Set OID (ST)> & <Alternate Value Set Version ID (DTM)> & <Second Alternate Coding System OID (ST)> & <Second Alternate Value Set OID (ST)> & <Second Alternate Value Set Version ID (DTM)>

Definition: This field identifies the person who originated (i.e., dictated) the document. The document originator may differ from the person responsible for authenticating the document.

==== 9.7.3.10 TXA-10 Assigned Document Authenticator (XCN) 00923

Components: <Person Identifier (ST)> ^ <Family Name (FN)> ^ <Given Name (ST)> ^ <Second and Further Given Names or Initials Thereof (ST)> ^ <Suffix (e.g., JR or III) (ST)> ^ <Prefix (e.g., DR) (ST)> ^ <WITHDRAWN Constituent> ^ <DEPRECATED-Source Table (CWE)> ^ <Assigning Authority (HD)> ^ <Name Type Code (ID)> ^ <Identifier Check Digit (ST)> ^ <Check Digit Scheme (ID)> ^ <Identifier Type Code (ID)> ^ <Assigning Facility (HD)> ^ <Name Representation Code (ID)> ^ <Name Context (CWE)> ^ <WITHDRAWN Constituent> ^ <Name Assembly Order (ID)> ^ <Effective Date (DTM)> ^ <Expiration Date (DTM)> ^ <Professional Suffix (ST)> ^ <Assigning Jurisdiction (CWE)> ^ <Assigning Agency or Department (CWE)> ^ <Security Check (ST)> ^ <Security Check Scheme (ID)>

Subcomponents for Family Name (FN): <Surname (ST)> & <Own Surname Prefix (ST)> & <Own Surname (ST)> & <Surname Prefix from Partner/Spouse (ST)> & <Surname from Partner/Spouse (ST)>

Subcomponents for Source Table (CWE): <Identifier (ST)> & <Text (ST)> & <Name of Coding System (ID)> & <Alternate Identifier (ST)> & <Alternate Text (ST)> & <Name of Alternate Coding System (ID)> & <Coding System Version ID (ST)> & <Alternate Coding System Version ID (ST)> & <Original Text (ST)> & <Second Alternate Identifier (ST)> & <Second Alternate Text (ST)> & <Name of Second Alternate Coding System (ID)> & <Second Alternate Coding System Version ID (ST)> & <Coding System OID (ST)> & <Value Set OID (ST)> & <Value Set Version ID (DTM)> & <Alternate Coding System OID (ST)> & <Alternate Value Set OID (ST)> & <Alternate Value Set Version ID (DTM)> & <Second Alternate Coding System OID (ST)> & <Second Alternate Value Set OID (ST)> & <Second Alternate Value Set Version ID (DTM)>

Subcomponents for Assigning Authority (HD): <Namespace ID (IS)> & <Universal ID (ST)> & <Universal ID Type (ID)>

Subcomponents for Assigning Facility (HD): <Namespace ID (IS)> & <Universal ID (ST)> & <Universal ID Type (ID)>

Subcomponents for Name Context (CWE): <Identifier (ST)> & <Text (ST)> & <Name of Coding System (ID)> & <Alternate Identifier (ST)> & <Alternate Text (ST)> & <Name of Alternate Coding System (ID)> & <Coding System Version ID (ST)> & <Alternate Coding System Version ID (ST)> & <Original Text (ST)> & <Second Alternate Identifier (ST)> & <Second Alternate Text (ST)> & <Name of Second Alternate Coding System (ID)> & <Second Alternate Coding System Version ID (ST)> & <Coding System OID (ST)> & <Value Set OID (ST)> & <Value Set Version ID (DTM)> & <Alternate Coding System OID (ST)> & <Alternate Value Set OID (ST)> & <Alternate Value Set Version ID (DTM)> & <Second Alternate Coding System OID (ST)> & <Second Alternate Value Set OID (ST)> & <Second Alternate Value Set Version ID (DTM)>

Subcomponents for Assigning Jurisdiction (CWE): <Identifier (ST)> & <Text (ST)> & <Name of Coding System (ID)> & <Alternate Identifier (ST)> & <Alternate Text (ST)> & <Name of Alternate Coding System (ID)> & <Coding System Version ID (ST)> & <Alternate Coding System Version ID (ST)> & <Original Text (ST)> & <Second Alternate Identifier (ST)> & <Second Alternate Text (ST)> & <Name of Second Alternate Coding System (ID)> & <Second Alternate Coding System Version ID (ST)> & <Coding System OID (ST)> & <Value Set OID (ST)> & <Value Set Version ID (DTM)> & <Alternate Coding System OID (ST)> & <Alternate Value Set OID (ST)> & <Alternate Value Set Version ID (DTM)> & <Second Alternate Coding System OID (ST)> & <Second Alternate Value Set OID (ST)> & <Second Alternate Value Set Version ID (DTM)>

Subcomponents for Assigning Agency or Department (CWE): <Identifier (ST)> & <Text (ST)> & <Name of Coding System (ID)> & <Alternate Identifier (ST)> & <Alternate Text (ST)> & <Name of Alternate Coding System (ID)> & <Coding System Version ID (ST)> & <Alternate Coding System Version ID (ST)> & <Original Text (ST)> & <Second Alternate Identifier (ST)> & <Second Alternate Text (ST)> & <Name of Second Alternate Coding System (ID)> & <Second Alternate Coding System Version ID (ST)> & <Coding System OID (ST)> & <Value Set OID (ST)> & <Value Set Version ID (DTM)> & <Alternate Coding System OID (ST)> & <Alternate Value Set OID (ST)> & <Alternate Value Set Version ID (DTM)> & <Second Alternate Coding System OID (ST)> & <Second Alternate Value Set OID (ST)> & <Second Alternate Value Set Version ID (DTM)>

Definition: This field identifies the person(s) responsible for authenticating the document, who may differ from the originator. Multiple persons may be responsible for authentication, especially in teaching facilities. This field is allowed to repeat an undefined number of times.

==== 9.7.3.11 TXA-11 Transcriptionist Code/Name (XCN) 00924

Components: <Person Identifier (ST)> ^ <Family Name (FN)> ^ <Given Name (ST)> ^ <Second and Further Given Names or Initials Thereof (ST)> ^ <Suffix (e.g., JR or III) (ST)> ^ <Prefix (e.g., DR) (ST)> ^ <WITHDRAWN Constituent> ^ <DEPRECATED-Source Table (CWE)> ^ <Assigning Authority (HD)> ^ <Name Type Code (ID)> ^ <Identifier Check Digit (ST)> ^ <Check Digit Scheme (ID)> ^ <Identifier Type Code (ID)> ^ <Assigning Facility (HD)> ^ <Name Representation Code (ID)> ^ <Name Context (CWE)> ^ <WITHDRAWN Constituent> ^ <Name Assembly Order (ID)> ^ <Effective Date (DTM)> ^ <Expiration Date (DTM)> ^ <Professional Suffix (ST)> ^ <Assigning Jurisdiction (CWE)> ^ <Assigning Agency or Department (CWE)> ^ <Security Check (ST)> ^ <Security Check Scheme (ID)>

Subcomponents for Family Name (FN): <Surname (ST)> & <Own Surname Prefix (ST)> & <Own Surname (ST)> & <Surname Prefix from Partner/Spouse (ST)> & <Surname from Partner/Spouse (ST)>

Subcomponents for Source Table (CWE): <Identifier (ST)> & <Text (ST)> & <Name of Coding System (ID)> & <Alternate Identifier (ST)> & <Alternate Text (ST)> & <Name of Alternate Coding System (ID)> & <Coding System Version ID (ST)> & <Alternate Coding System Version ID (ST)> & <Original Text (ST)> & <Second Alternate Identifier (ST)> & <Second Alternate Text (ST)> & <Name of Second Alternate Coding System (ID)> & <Second Alternate Coding System Version ID (ST)> & <Coding System OID (ST)> & <Value Set OID (ST)> & <Value Set Version ID (DTM)> & <Alternate Coding System OID (ST)> & <Alternate Value Set OID (ST)> & <Alternate Value Set Version ID (DTM)> & <Second Alternate Coding System OID (ST)> & <Second Alternate Value Set OID (ST)> & <Second Alternate Value Set Version ID (DTM)>

Subcomponents for Assigning Authority (HD): <Namespace ID (IS)> & <Universal ID (ST)> & <Universal ID Type (ID)>

Subcomponents for Assigning Facility (HD): <Namespace ID (IS)> & <Universal ID (ST)> & <Universal ID Type (ID)>

Subcomponents for Name Context (CWE): <Identifier (ST)> & <Text (ST)> & <Name of Coding System (ID)> & <Alternate Identifier (ST)> & <Alternate Text (ST)> & <Name of Alternate Coding System (ID)> & <Coding System Version ID (ST)> & <Alternate Coding System Version ID (ST)> & <Original Text (ST)> & <Second Alternate Identifier (ST)> & <Second Alternate Text (ST)> & <Name of Second Alternate Coding System (ID)> & <Second Alternate Coding System Version ID (ST)> & <Coding System OID (ST)> & <Value Set OID (ST)> & <Value Set Version ID (DTM)> & <Alternate Coding System OID (ST)> & <Alternate Value Set OID (ST)> & <Alternate Value Set Version ID (DTM)> & <Second Alternate Coding System OID (ST)> & <Second Alternate Value Set OID (ST)> & <Second Alternate Value Set Version ID (DTM)>

Subcomponents for Assigning Jurisdiction (CWE): <Identifier (ST)> & <Text (ST)> & <Name of Coding System (ID)> & <Alternate Identifier (ST)> & <Alternate Text (ST)> & <Name of Alternate Coding System (ID)> & <Coding System Version ID (ST)> & <Alternate Coding System Version ID (ST)> & <Original Text (ST)> & <Second Alternate Identifier (ST)> & <Second Alternate Text (ST)> & <Name of Second Alternate Coding System (ID)> & <Second Alternate Coding System Version ID (ST)> & <Coding System OID (ST)> & <Value Set OID (ST)> & <Value Set Version ID (DTM)> & <Alternate Coding System OID (ST)> & <Alternate Value Set OID (ST)> & <Alternate Value Set Version ID (DTM)> & <Second Alternate Coding System OID (ST)> & <Second Alternate Value Set OID (ST)> & <Second Alternate Value Set Version ID (DTM)>

Subcomponents for Assigning Agency or Department (CWE): <Identifier (ST)> & <Text (ST)> & <Name of Coding System (ID)> & <Alternate Identifier (ST)> & <Alternate Text (ST)> & <Name of Alternate Coding System (ID)> & <Coding System Version ID (ST)> & <Alternate Coding System Version ID (ST)> & <Original Text (ST)> & <Second Alternate Identifier (ST)> & <Second Alternate Text (ST)> & <Name of Second Alternate Coding System (ID)> & <Second Alternate Coding System Version ID (ST)> & <Coding System OID (ST)> & <Value Set OID (ST)> & <Value Set Version ID (DTM)> & <Alternate Coding System OID (ST)> & <Alternate Value Set OID (ST)> & <Alternate Value Set Version ID (DTM)> & <Second Alternate Coding System OID (ST)> & <Second Alternate Value Set OID (ST)> & <Second Alternate Value Set Version ID (DTM)>

Definition: This field identifies the person transcribing the document. This is a conditional value; it is required on all transcribed documents.

TXA-11 - Condition: If TXA-11 is valued and the corresponding OBR segment is present in the message OBR-35 must be blank. If OBR-35 is valued while TXA-11 is valued, OBR-35 shall be ignored. See message definitions including TXA for further guidanceon which ORC/OBR pairs to consider.

==== 9.7.3.12 TXA-12 Unique Document Number (EI) 00925

Components: <Entity Identifier (ST)> ^ <Namespace ID (IS)> ^ <Universal ID (ST)> ^ <Universal ID Type (ID)>

Definition: This field contains a unique document identification number assigned by the sending system. This document number is used to assist the receiving system in matching future updates to the document, as well as to identify the document in a query. When the vendor does not provide a unique document ID number, some type of document identifier should be entered here, or the Unique Document File name should be utilized. See Chapter 2A, section 2.A.89, "XTN - extended telecommunication number." Where the system does not customarily have a document filler number, this number could serve as that value, as well.

==== 9.7.3.13 TXA-13 Parent Document Number (EI) 00926

Components: <Entity Identifier (ST)> ^ <Namespace ID (IS)> ^ <Universal ID (ST)> ^ <Universal ID Type (ID)>

Definition: This field contains a document number that identifies the parent document to which this document belongs. The parent document number can be used to assist the receiving system in matching future updates to this document. This is a conditional field that is always required on T05 (document addendum notification), T06 (document addendum notification and content), T09 (document replacement notification), and T10 (document replacement notification and content) events.

==== 9.7.3.14 TXA-14 Placer Order Number (EI) 00216

Components: <Entity Identifier (ST)> ^ <Namespace ID (IS)> ^ <Universal ID (ST)> ^ <Universal ID Type (ID)>

Definition: This field is the placer application's order number.

This is a composite field. The first component is a string of characters that identifies an individual order (i.e., OBR). It is assigned by the placer (ordering application). It identifies an order uniquely among all orders from a particular ordering application. The second through fourth components contain the (filler) assigning authority of the placing application. The (filler) assigning authority is a string of characters that will be uniquely associated with an application. A given institution or group of intercommunicating institutions should establish a unique list of applications that may be potential placers and fillers and assign unique entity identifiers. The components are separated by component delimiters.

TXA-14 - Condition: If corresponding ORC and/or OBR segments are present in the message and ORC-2 or OBR-2 is valued, this field must be blank. If TXA-14 is valued while ORC-2 or OBR-2 is valued it shall be ignored. See message definitions including TXA for further guidance on which ORC/OBR pairs to consider.

==== 9.7.3.15 TXA-15 Filler Order Number (EI) 00217

Components: <Entity Identifier (ST)> ^ <Namespace ID (IS)> ^ <Universal ID (ST)> ^ <Universal ID Type (ID)>

Definition: This field is the order number associated with the filling application. Where a transcription service or similar organization creates the document and uses an internally unique identifier, that number should be inserted in this field. Its first component is a string of characters that identifies an order detail segment (i.e., OBR). This string must uniquely identify the order (as specified in the order detail segment) from other orders in a particular filling application (i.e., transcription service). This uniqueness must persist over time. Where a number is reused over time, a date can be affixed to the non-unique number to make it unique.

The second through fourth components contains the (filler) assigning authority. The (filler) assigning authority is a string of characters that uniquely defines the application from other applications on the network. The second through fourth components of the filler order number always identify the actual filler of an order.

TXA-15 - Condition: If corresponding ORC and/or OBR segments are present in the message and ORC-3 or OBR-3 is valued, this field must be blank. If TXA-14 is valued while ORC-3 or OBR-3 is valued it shall be ignored. See message definitions including TXA for further guidanceon which ORC/OBR pairs to consider.

For further details, please see the definitions provided in Chapter 4, "Orders".

==== 9.7.3.16 TXA-16 Unique Document File Name (ST) 00927

Definition: This field contains a unique name assigned to a document by the sending system. The file name is used to assist the receiving system in matching future updates to the document.

==== 9.7.3.17 TXA-17 Document Completion Status (ID) 00928

Definition: This field identifies the current completion state of the document. This is a required, table-driven field. Refer to file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70271[_HL7 Table 0271 - Document Completion Status_] for valid values.

Figure 9-1. Document completion status state transition table

[width="100%",cols="46%,24%,30%",options="header",]
|===
|Transition (Action) |Old State |New State
a|
T01 Original Notification

T02 Original Notification and Content

|NA a|
Dictated

In Progress

Incomplete

Pre-authenticated

Authenticated

Legally authenticated

a|
T03 Status Change Notification

T04 Status Change Notification and Content

|Dictated a|
In Progress

Incomplete

Pre-authenticated

Authenticated

Legally authenticated

| |In Progress a|
Incomplete

Pre-authenticated

Authenticated

Legally authenticated

| |Incomplete a|
Pre-authenticated

Authenticated

Legally authenticated

| |Pre-authenticated a|
Authenticated

Legally authenticated

| |Authenticated |Legally authenticated
| |Legally authenticated |NA
| |Documented a|
Pre-authenticated

Authenticated

Legally authenticated

a|
T05 Addendum Notification

T06 Addendum Notification and Content

|NA a|
Dictated

In Progress

Incomplete

Pre-authenticated

Authenticated

Legally authenticated

a|
T07 Edit Notification

T08 Edit Notification and Content

|Dictated a|
In Progress

Incomplete

Pre-authenticated

Authenticated

Legally authenticated

| |In Progress a|
Incomplete

Pre-authenticated

Authenticated

Legally authenticated

| |Incomplete a|
Pre-authenticated

Authenticated

Legally authenticated

| |Pre-authenticated a|
Authenticated

Legally authenticated

| |Authenticated |Legally authenticated
| |Legally authenticated |NA
| |Documented a|
Pre-authenticated

Authenticated

Legally authenticated

a|
T09 Replacement Notification

T10 Replacement Notification and Content

|NA a|
Dictated

In Progress

Incomplete

Pre-authenticated

Authenticated

Legally authenticated

|T11 Cancel Notification |Dictated +
In Progress +
Incomplete +
Pre-authenticated +
and Availability status of "Unavailable" |Canceled
|===

==== 9.7.3.18 TXA-18 Document Confidentiality Status (ID) 00929

Definition: This is an optional field which identifies the degree to which special confidentiality protection should be applied to this information. The assignment of data elements to these categories is left to the discretion of the healthcare organization. Refer to file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70272[_HL7 Table 0272 - Document Confidentiality Status_] for valid values.

==== 9.7.3.19 TXA-19 Document Availability Status (ID) 00930

Definition: This is an optional field which identifies a document's availability for use in patient care. If an organization's business rules allow a document to be used for patient care before it is authenticated, the value of this field should be set to "AV." If a document has been made available for patient care, it cannot be changed or deleted. If an erroneous document has been made available at any point in time and a replacement is not appropriate, then it may be marked as "Canceled" and removed, as in the case of a document being assigned to the wrong patient. Additional information must be provided via an addendum, which is separately authenticated and date/time stamped. If the content of a document whose status is "Available" must be revised, this is done by issuing a replacement, which is separately authenticated and date/time stamped. Refer to file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70273[_HL7 Table 0273 - Document Availability Status_] for valid values.

Figure 9-2. Document availability status state transition table

[width="100%",cols="48%,15%,15%,22%",options="header",]
|===
|Transition (Action) |Old State |New State |Notes
a|
T01 Original Notification

T02 Original Notification and Content

|NA a|
Unavailable

Available

|
a|
T03 Status Change Notification

T04 Status Change Notification and Content

|Unavailable a|
Unavailable

Available

Obsolete

|
| |Available a|
Available

Obsolete

|
| |Obsolete |NA |
a|
T05 Addendum Notification

T06 Addendum Notification and Content

|NA a|
Unavailable

Available

|
a|
T07 Edit Notification

T08 Edit Notification and Content

|Unavailable a|
Unavailable

Available

|
a|
T09 Replacement Notification

T10 Replacement Notification and Content

|NA a|
Unavailable

Available

|Set parent document to "obsolete"
|T11 Cancel |Unavailable |Delete |
|===

*Note:* NA means not applicable.

==== 9.7.3.20 TXA-20 Document Storage Status (ID) 00932

Definition: This optional field identifies the storage status of the document. Refer to file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70275[_HL7 Table 0275 - Document Storage Status_] for valid values.

==== 9.7.3.21 TXA-21 Document Change Reason (ST) 00933

Definition: This free text field (limited to 30 characters) contains the reason for document status change.

==== 9.7.3.22 TXA-22 Authentication Person, Time Stamp (set) (PPN) 00934

Components: <Person Identifier (ST)> ^ <Family Name (FN)> ^ <Given Name (ST)> ^ <Second and Further Given Names or Initials Thereof (ST)> ^ <Suffix (e.g., JR or III) (ST)> ^ <Prefix (e.g., DR) (ST)> ^ <WITHDRAWN Constituent> ^ <DEPRECATED-Source Table (CWE)> ^ <Assigning Authority (HD)> ^ <Name Type Code (ID)> ^ <Identifier Check Digit (ST)> ^ <Check Digit Scheme (ID)> ^ <Identifier Type Code (ID)> ^ <Assigning Facility (HD)> ^ <Date/Time Action Performed (DTM)> ^ <Name Representation Code (ID)> ^ <Name Context (CWE)> ^ <WITHDRAWN Constituent> ^ <Name Assembly Order (ID)> ^ <Effective Date (DTM)> ^ <Expiration Date (DTM)> ^ <Professional Suffix (ST)> ^ <Assigning Jurisdiction (CWE)> ^ <Assigning Agency or Department (CWE)> ^ <Security Check (ST)> ^ <Security Check Scheme (ID)>

Subcomponents for Family Name (FN): <Surname (ST)> & <Own Surname Prefix (ST)> & <Own Surname (ST)> & <Surname Prefix from Partner/Spouse (ST)> & <Surname from Partner/Spouse (ST)>

Subcomponents for Source Table (CWE): <Identifier (ST)> & <Text (ST)> & <Name of Coding System (ID)> & <Alternate Identifier (ST)> & <Alternate Text (ST)> & <Name of Alternate Coding System (ID)> & <Coding System Version ID (ST)> & <Alternate Coding System Version ID (ST)> & <Original Text (ST)> & <Second Alternate Identifier (ST)> & <Second Alternate Text (ST)> & <Name of Second Alternate Coding System (ID)> & <Second Alternate Coding System Version ID (ST)> & <Coding System OID (ST)> & <Value Set OID (ST)> & <Value Set Version ID (DTM)> & <Alternate Coding System OID (ST)> & <Alternate Value Set OID (ST)> & <Alternate Value Set Version ID (DTM)> & <Second Alternate Coding System OID (ST)> & <Second Alternate Value Set OID (ST)> & <Second Alternate Value Set Version ID (DTM)>

Subcomponents for Assigning Authority (HD): <Namespace ID (IS)> & <Universal ID (ST)> & <Universal ID Type (ID)>

Subcomponents for Assigning Facility (HD): <Namespace ID (IS)> & <Universal ID (ST)> & <Universal ID Type (ID)>

Subcomponents for Name Context (CWE): <Identifier (ST)> & <Text (ST)> & <Name of Coding System (ID)> & <Alternate Identifier (ST)> & <Alternate Text (ST)> & <Name of Alternate Coding System (ID)> & <Coding System Version ID (ST)> & <Alternate Coding System Version ID (ST)> & <Original Text (ST)> & <Second Alternate Identifier (ST)> & <Second Alternate Text (ST)> & <Name of Second Alternate Coding System (ID)> & <Second Alternate Coding System Version ID (ST)> & <Coding System OID (ST)> & <Value Set OID (ST)> & <Value Set Version ID (DTM)> & <Alternate Coding System OID (ST)> & <Alternate Value Set OID (ST)> & <Alternate Value Set Version ID (DTM)> & <Second Alternate Coding System OID (ST)> & <Second Alternate Value Set OID (ST)> & <Second Alternate Value Set Version ID (DTM)>

Subcomponents for Assigning Jurisdiction (CWE): <Identifier (ST)> & <Text (ST)> & <Name of Coding System (ID)> & <Alternate Identifier (ST)> & <Alternate Text (ST)> & <Name of Alternate Coding System (ID)> & <Coding System Version ID (ST)> & <Alternate Coding System Version ID (ST)> & <Original Text (ST)> & <Second Alternate Identifier (ST)> & <Second Alternate Text (ST)> & <Name of Second Alternate Coding System (ID)> & <Second Alternate Coding System Version ID (ST)> & <Coding System OID (ST)> & <Value Set OID (ST)> & <Value Set Version ID (DTM)> & <Alternate Coding System OID (ST)> & <Alternate Value Set OID (ST)> & <Alternate Value Set Version ID (DTM)> & <Second Alternate Coding System OID (ST)> & <Second Alternate Value Set OID (ST)> & <Second Alternate Value Set Version ID (DTM)>

Subcomponents for Assigning Agency or Department (CWE): <Identifier (ST)> & <Text (ST)> & <Name of Coding System (ID)> & <Alternate Identifier (ST)> & <Alternate Text (ST)> & <Name of Alternate Coding System (ID)> & <Coding System Version ID (ST)> & <Alternate Coding System Version ID (ST)> & <Original Text (ST)> & <Second Alternate Identifier (ST)> & <Second Alternate Text (ST)> & <Name of Second Alternate Coding System (ID)> & <Second Alternate Coding System Version ID (ST)> & <Coding System OID (ST)> & <Value Set OID (ST)> & <Value Set Version ID (DTM)> & <Alternate Coding System OID (ST)> & <Alternate Value Set OID (ST)> & <Alternate Value Set Version ID (DTM)> & <Second Alternate Coding System OID (ST)> & <Second Alternate Value Set OID (ST)> & <Second Alternate Value Set Version ID (DTM)>

Definition: This field contains a set of components describing by whom and when authentication was performed (either manually or electronically). The Date/Time Action Performed component describes the date/time of the authentication (Authentication Time Stamp). The remaining components identify the person performing the authentication (Authentication Person). If either of the Authenticating Person or the Authentication Time Stamp is valued as non-null, then both must be valued as non-null.

TXA-22 - Condition: If TXA-22 is valued and the corresponding OBR segment is present in the message OBR-32 must be blank. If OBR-32 is valued while TXA-22 is valued, OBR-32 shall be ignored. See message definitions including TXA for further guidanceon which ORC/OBR pairs to consider.

==== 9.7.3.23 TXA-23 Distributed Copies (Code and Name of Recipients(s)) (XCN) 00935

Components: <Person Identifier (ST)> ^ <Family Name (FN)> ^ <Given Name (ST)> ^ <Second and Further Given Names or Initials Thereof (ST)> ^ <Suffix (e.g., JR or III) (ST)> ^ <Prefix (e.g., DR) (ST)> ^ <WITHDRAWN Constituent> ^ <DEPRECATED-Source Table (CWE)> ^ <Assigning Authority (HD)> ^ <Name Type Code (ID)> ^ <Identifier Check Digit (ST)> ^ <Check Digit Scheme (ID)> ^ <Identifier Type Code (ID)> ^ <Assigning Facility (HD)> ^ <Name Representation Code (ID)> ^ <Name Context (CWE)> ^ <WITHDRAWN Constituent> ^ <Name Assembly Order (ID)> ^ <Effective Date (DTM)> ^ <Expiration Date (DTM)> ^ <Professional Suffix (ST)> ^ <Assigning Jurisdiction (CWE)> ^ <Assigning Agency or Department (CWE)> ^ <Security Check (ST)> ^ <Security Check Scheme (ID)>

Subcomponents for Family Name (FN): <Surname (ST)> & <Own Surname Prefix (ST)> & <Own Surname (ST)> & <Surname Prefix from Partner/Spouse (ST)> & <Surname from Partner/Spouse (ST)>

Subcomponents for Source Table (CWE): <Identifier (ST)> & <Text (ST)> & <Name of Coding System (ID)> & <Alternate Identifier (ST)> & <Alternate Text (ST)> & <Name of Alternate Coding System (ID)> & <Coding System Version ID (ST)> & <Alternate Coding System Version ID (ST)> & <Original Text (ST)> & <Second Alternate Identifier (ST)> & <Second Alternate Text (ST)> & <Name of Second Alternate Coding System (ID)> & <Second Alternate Coding System Version ID (ST)> & <Coding System OID (ST)> & <Value Set OID (ST)> & <Value Set Version ID (DTM)> & <Alternate Coding System OID (ST)> & <Alternate Value Set OID (ST)> & <Alternate Value Set Version ID (DTM)> & <Second Alternate Coding System OID (ST)> & <Second Alternate Value Set OID (ST)> & <Second Alternate Value Set Version ID (DTM)>

Subcomponents for Assigning Authority (HD): <Namespace ID (IS)> & <Universal ID (ST)> & <Universal ID Type (ID)>

Subcomponents for Assigning Facility (HD): <Namespace ID (IS)> & <Universal ID (ST)> & <Universal ID Type (ID)>

Subcomponents for Name Context (CWE): <Identifier (ST)> & <Text (ST)> & <Name of Coding System (ID)> & <Alternate Identifier (ST)> & <Alternate Text (ST)> & <Name of Alternate Coding System (ID)> & <Coding System Version ID (ST)> & <Alternate Coding System Version ID (ST)> & <Original Text (ST)> & <Second Alternate Identifier (ST)> & <Second Alternate Text (ST)> & <Name of Second Alternate Coding System (ID)> & <Second Alternate Coding System Version ID (ST)> & <Coding System OID (ST)> & <Value Set OID (ST)> & <Value Set Version ID (DTM)> & <Alternate Coding System OID (ST)> & <Alternate Value Set OID (ST)> & <Alternate Value Set Version ID (DTM)> & <Second Alternate Coding System OID (ST)> & <Second Alternate Value Set OID (ST)> & <Second Alternate Value Set Version ID (DTM)>

Subcomponents for Assigning Jurisdiction (CWE): <Identifier (ST)> & <Text (ST)> & <Name of Coding System (ID)> & <Alternate Identifier (ST)> & <Alternate Text (ST)> & <Name of Alternate Coding System (ID)> & <Coding System Version ID (ST)> & <Alternate Coding System Version ID (ST)> & <Original Text (ST)> & <Second Alternate Identifier (ST)> & <Second Alternate Text (ST)> & <Name of Second Alternate Coding System (ID)> & <Second Alternate Coding System Version ID (ST)> & <Coding System OID (ST)> & <Value Set OID (ST)> & <Value Set Version ID (DTM)> & <Alternate Coding System OID (ST)> & <Alternate Value Set OID (ST)> & <Alternate Value Set Version ID (DTM)> & <Second Alternate Coding System OID (ST)> & <Second Alternate Value Set OID (ST)> & <Second Alternate Value Set Version ID (DTM)>

Subcomponents for Assigning Agency or Department (CWE): <Identifier (ST)> & <Text (ST)> & <Name of Coding System (ID)> & <Alternate Identifier (ST)> & <Alternate Text (ST)> & <Name of Alternate Coding System (ID)> & <Coding System Version ID (ST)> & <Alternate Coding System Version ID (ST)> & <Original Text (ST)> & <Second Alternate Identifier (ST)> & <Second Alternate Text (ST)> & <Name of Second Alternate Coding System (ID)> & <Second Alternate Coding System Version ID (ST)> & <Coding System OID (ST)> & <Value Set OID (ST)> & <Value Set Version ID (DTM)> & <Alternate Coding System OID (ST)> & <Alternate Value Set OID (ST)> & <Alternate Value Set Version ID (DTM)> & <Second Alternate Coding System OID (ST)> & <Second Alternate Value Set OID (ST)> & <Second Alternate Value Set Version ID (DTM)>

Definition: This field identifies the persons who received a copy of this document.

==== 9.7.3.24 TXA-24 Folder Assignment (CWE) 02378

Components: <Identifier (ST)> ^ <Text (ST)> ^ <Name of Coding System (ID)> ^ <Alternate Identifier (ST)> ^ <Alternate Text (ST)> ^ <Name of Alternate Coding System (ID)> ^ <Coding System Version ID (ST)> ^ <Alternate Coding System Version ID (ST)> ^ <Original Text (ST)> ^ <Second Alternate Identifier (ST)> ^ <Second Alternate Text (ST)> ^ <Name of Second Alternate Coding System (ID)> ^ <Second Alternate Coding System Version ID (ST)> ^ <Coding System OID (ST)> ^ <Value Set OID (ST)> ^ <Value Set Version ID (DTM)> ^ <Alternate Coding System OID (ST)> ^ <Alternate Value Set OID (ST)> ^ <Alternate Value Set Version ID (DTM)> ^ <Second Alternate Coding System OID (ST)> ^ <Second Alternate Value Set OID (ST)> ^ <Second Alternate Value Set Version ID (DTM)>

Definition: This field is used to assign documents to folders. These folders are not nested; a document may either be part of none or several folders. In practice this can be used to separate the documents into domain specific types (e.g., cardiology reports, radiology reports), organizational types (e.g., administrational document, billing document), body region types (e.g., chest CT, leg CT), or something else. Furthermore, this information can be combined. This usually depends on the system involved and therefore it must be up to the user to define it. The systems can use the information to define workflows or manage access to the document. Receivers are required to inspect the Coding System component of the CWE data type to accurately interpret the meaning of the code. Senders transmitting messages to Receivers on earlier version of the standard may elect to negotiate business rules to ensure that expected data is not lost. HL7 does not assign positional meaning to user-defined codes. Refer to Table 0791 - Folder Assignment in Chapter 2C for valid values.

==== 9.7.3.25 TXA-25 Document Title (ST) 03301

Definition: This field supports the identification of the document title. When communicating the meta information without the document contents you may submit the document title as well.

==== 9.7.3.26 TXA-26 Agreed Due Date/Time (DTM) 03302

Definition: This field contains the date and time the document is or will be due back to the original author or dictator from the transcriptionist.

==== 9.7.3.27 TXA-27 Creating Facility (HD) 02413

Components: <Namespace ID (IS)> ^ <Universal ID (ST)> ^ <Universal ID Type (ID)>

Definition: This field identifies the facility in which this document has been created.

==== 9.7.3.28 TXA-28 Creating Specialty (CWE) 02414

Components: <Identifier (ST)> ^ <Text (ST)> ^ <Name of Coding System (ID)> ^ <Alternate Identifier (ST)> ^ <Alternate Text (ST)> ^ <Name of Alternate Coding System (ID)> ^ <Coding System Version ID (ST)> ^ <Alternate Coding System Version ID (ST)> ^ <Original Text (ST)> ^ <Second Alternate Identifier (ST)> ^ <Second Alternate Text (ST)> ^ <Name of Second Alternate Coding System (ID)> ^ <Second Alternate Coding System Version ID (ST)> ^ <Coding System OID (ST)> ^ <Value Set OID (ST)> ^ <Value Set Version ID (DTM)> ^ <Alternate Coding System OID (ST)> ^ <Alternate Value Set OID (ST)> ^ <Alternate Value Set Version ID (DTM)> ^ <Second Alternate Coding System OID (ST)> ^ <Second Alternate Value Set OID (ST)> ^ <Second Alternate Value Set Version ID (DTM)>

Definition: This field identifies the specialty of the provider which created this document. Refer to Table 0792 - Creating Specialty in Chapter 2C for valid values.

____
*Note*: There are no suggested values for speciality.
____

==== 9.7.3.29 TXA-29 Document Class (CWE) 02530

Components: <Identifier (ST)> ^ <Text (ST)> ^ <Name of Coding System (ID)> ^ <Alternate Identifier (ST)> ^ <Alternate Text (ST)> ^ <Name of Alternate Coding System (ID)> ^ <Coding System Version ID (ST)> ^ <Alternate Coding System Version ID (ST)> ^ <Original Text (ST)> ^ <Second Alternate Identifier (ST)> ^ <Second Alternate Text (ST)> ^ <Name of Second Alternate Coding System (ID)> ^ <Second Alternate Coding System Version ID (ST)> ^ <Coding System OID (ST)> ^ <Value Set OID (ST)> ^ <Value Set Version ID (DTM)> ^ <Alternate Coding System OID (ST)> ^ <Alternate Value Set OID (ST)> ^ <Alternate Value Set Version ID (DTM)> ^ <Second Alternate Coding System OID (ST)> ^ <Second Alternate Value Set OID (ST)> ^ <Second Alternate Value Set Version ID (DTM)>

Definition: The code specifying the high-level use classification of the document type (e.g., Report, Summary, Images, Treatment Plan, Patient Preferences, Workflow). Refer to file:///C:\Users\cnewman\Downloads\V281_CH02C_CodeTables.doc#HL70270[_User-Defined Table 0832 - Document Class_] in Chapter 2C for suggested values.

==== 9.7.3.30 TXA-30 Document Event (CWE) 02531

Components: <Identifier (ST)> ^ <Text (ST)> ^ <Name of Coding System (ID)> ^ <Alternate Identifier (ST)> ^ <Alternate Text (ST)> ^ <Name of Alternate Coding System (ID)> ^ <Coding System Version ID (ST)> ^ <Alternate Coding System Version ID (ST)> ^ <Original Text (ST)> ^ <Second Alternate Identifier (ST)> ^ <Second Alternate Text (ST)> ^ <Name of Second Alternate Coding System (ID)> ^ <Second Alternate Coding System Version ID (ST)> ^ <Coding System OID (ST)> ^ <Value Set OID (ST)> ^ <Value Set Version ID (DTM)> ^ <Alternate Coding System OID (ST)> ^ <Alternate Value Set OID (ST)> ^ <Alternate Value Set Version ID (DTM)> ^ <Second Alternate Coding System OID (ST)> ^ <Second Alternate Value Set OID (ST)> ^ <Second Alternate Value Set Version ID (DTM)>

Definition: This list of codes represents the main clinical acts, such as a colonoscopy or an appendectomy, being documented. Refer to file:///C:\Users\cnewman\Downloads\V281_CH02C_CodeTables.doc#HL70270[_User-Defined Table 0833 – Document Event_] in Chapter 2C for suggested values.

==== 9.7.3.31 TXA-31 Folder Instance Association (EI) 02532

Components: <Entity Identifier (ST)> ^ <Namespace ID (IS)> ^ <Universal ID (ST)> ^ <Universal ID Type (ID)>

Definition: This field contains a set of unique folder identification numbers that are associated with a document. This folder instance number is used to assist all systems to manage the documents by allowing for filtering, grouping, access control or other use cases.

== 9.8 EXAMPLE MESSAGES

=== 9.8.1 History and Physical Exam:

The following is an example of an original transmission of a history and physical examination which has been authenticated prior to this message being initiated:

MSH|...<cr>

EVN|T02|19960215154405||04|097220^Seven^Henry^L^ ^Dr^MD^| <cr>

PID|...<cr>

PR1|...<cr>

TXA|0001|HP^history & physical|TX^text|19960213213000|099919^Everyman^Adam^A^ ^Mr^MS^| +
19960213153000|19960215134500||099919^Everyman^Adam^A^III^Mr^MS^|097220^Seven^Henry^L^ ^Dr^MD^|01234567^Contact^Carrie^C^Ms|1996021500001^transA|||example.doc|LA|UC|AV||AC|||||097220^Seven^Henry^L^ ^Dr^MD^| <cr>

OBX|1|CE|2000.40^CHIEF COMPLAINT|| ... <cr>

OBX|2|ST|2000.01^SOURCE||PATIENT <cr>

OBX|3|TX|2000.02^PRESENT ILLNESS||SUDDEN ONSET OF CHEST PAIN. 2 DAYS, PTA ASSOCIATED WITH NAUSEA, VOMITING & SOB. NO RELIEF WITH ANTACIDS OR NTG. NO OTHER SX. NOT PREVIOUSLY ILL.<cr>

.

.

and so on.

=== 9.8.2 Document Folder 

____
Hospital A creates a psychiatric report. It sends a notification to hospital B.
____

MSH|^~\&|SENDAPP|SENDFAC|RECAPP|RECFAC|200411261008||MDM^T01^MDM_T01|167865|P|2.9

EVN|T01|200811261007|200811261007|60012|10107

PID|1|1011684|1011684||Jurgensen^Antoine^^||197710220000|F|||Hubertweg^^Stuttgart^^70173^DE|||||M|CAT||4390271065||||Karlsruhe|N||

PV1|1|I|STATION^^^3200^^13372100|A^^301||||||||||||N|||0460005110||K|||||||||||||||||||||||200811160916|||||

TXA|1|Psychiatric Disabilities Report|PDF|||||20081126100756 ||||570531^SENDFAC||||1081007_2874942_570531_26100756.PDF|DO|||||||PSY^psychiatric document^^1.2.4481222~WEB^web document^^1.2.4481223

Hospital B receives the document. Hospital A and B have negotiated the folder definitions in the form of a catalog (the exchange is out of scope of this document). Therefore, Hospital B knows the document should only be accessible to psychiatrists and should be available in the patient's personal web access. This is only an example; document folder interpretation is up to the systems and out of scope of this proposal.

== 9.9 QUERY

A query may be used to retrieve a list of documents or a specific document. See Chapter 5, "Queries", for details of queries.

=== 9.9.1 QRY/DOC - Document Query (Event T12)

Withdrawn in v2.7 and later; refer to Chapter 5, "Queries", section 5.4 instead.

== 9.10 OUTSTANDING ISSUES

This version of the standard clarifies the use of MDM message as opposed to ORU messages. Refer to Chapter 7, "Observations".
