==== 7.4.2.11 OBX-11 Observation Result Status (ID) 00579

Definition: This field contains the observation result status. Refer to file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70085[_HL7 table 0085 - Observation result status codes interpretation_] for valid values. This field reflects the current completion status of the results for one Observation Identifier.

It is a required field. Previous versions of HL7 stated this implicitly by defining a default value of "F." Code *F* indicates that the result has been verified to be correct and final. Code *W* indicates that the result has been verified to be wrong (incorrect); a replacement (corrected) result may be transmitted later. Code *C* indicates that data contained in the _OBX-5-observation value_ field are to replace previously transmitted (verified and) final result data with the same observation ID (including suffix, if applicable) and observation sub-ID usually because the previous results were wrong. Code *D* indicates that data previously transmitted in a result segment with the same observation ID (including suffix) and observation sub-ID should be deleted. When changing or deleting a result, multiple OBX segments with the same observation ID and observation sub-ID are replaced or deleted as a unit. Normal progression of results through intermediate (e.g., 'gram positive cocci') to final (e.g., 'staphylococcus aureus') should not be transmitted as *C* (correction); they should be transmitted as *P* (depending upon the specific case) until they are final.

If an observation involves multiple OBX segments with the same observation ID (including suffix) and observation sub-ID, the observation result status applies to all OBX segments, except where the value is D or X. The value of D or X is applicable only to the individual OBX. All other OBX segments with the same Observation ID and observation sub-ID must have the same value.

In the case of coding systems such as LOINC, the preceding rules typically mean that this field applies to a single OBX segment.

There are situations where the observation battery required for the order needs to be dynamically specified at the time of ordering. That is, this battery is then defined by the set of OBX segments transmitted along with the order and generated by the placing system. For example, timed measurements of serum glucose challenge tests may vary among laboratories. One institution may report them at –30, -15, 0, 30, 60, and 120 minutes, while another may report them at –30, 0, 30, 60, 90, and 120 minutes. Master file entries may exist for each individual element of the battery but not for the battery itself. Another example may be Renin Studies where the specification may be done upon ordering without having a master file definition for each permutation of the possible element. The OBX segments in the ORM message can be used to create dynamic specifications to accommodate these permutations without defining pre-existing master file definitions for the battery itself. The result status field in the OBX can be used to indicate whether the OBX in the ORM message is used to provide a dynamic specification or is used to communicate a result as context to the order. The status of O shall be used to indicate that the OBX segment is used for a dynamic specification of the required result. An OBX used for a dynamic specification must contain the detailed examination code, units, etc., with _OBX-11_ valued with O, and _OBX-2_ and _OBX-5_ valued with null.

