==== 7.4.3.9 SPM-9 Specimen Source Site Modifier (CWE) 01760 

Components: <Identifier (ST)> ^ <Text (ST)> ^ <Name of Coding System (ID)> ^ <Alternate Identifier (ST)> ^ <Alternate Text (ST)> ^ <Name of Alternate Coding System (ID)> ^ <Coding System Version ID (ST)> ^ <Alternate Coding System Version ID (ST)> ^ <Original Text (ST)> ^ <Second Alternate Identifier (ST)> ^ <Second Alternate Text (ST)> ^ <Name of Second Alternate Coding System (ID)> ^ <Second Alternate Coding System Version ID (ST)> ^ <Coding System OID (ST)> ^ <Value Set OID (ST)> ^ <Value Set Version ID (DTM)> ^ <Alternate Coding System OID (ST)> ^ <Alternate Value Set OID (ST)> ^ <Alternate Value Set Version ID (DTM)> ^ <Second Alternate Coding System OID (ST)> ^ <Second Alternate Value Set OID (ST)> ^ <Second Alternate Value Set Version ID (DTM)>

Definition: This field contains modifying or qualifying description(s) about the specimen source site

The use of this attribute is to modify, qualify or further specify, the entity described by _SPM-8 – Specimen Source Site_. This is particularly useful when the code set used in _SPM-8_ does not provide the precision required to fully describe the site from which the specimen originated. For example, if the specimen source site was precisely described as 'left radial vein' but the code set employed only provided 'radial vein,' this attribute could be employed to add the modifier 'left.'

Veterinary medicine may choose the tables supported for the components of this field as decided by their industry.

Refer to file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70542[_User-Defined Table 0542 – Specimen Source Type Modifier_] for suggested values.

