==== 7.4.2.5 OBX-5 Observation Value (varies) 00573

Definition: This field contains the value observed by the observation producer. _OBX-2-value type_ contains the data type for this field according to which observation value is formatted. It is not a required field because some systems will report only the Interpretation Codes (_OBX-8_), especially in product experience reporting. The length of the observation field is variable, depending upon _OBX-2-value type_. This field may repeat for multipart, single answer results.

Representation

This field contains the value related to the _OBX-3-observation identifier_ of the same segment. Depending upon the observation, the data type may be a number (e.g., a respiratory rate), a coded answer (e.g., a pathology impression recorded as SNOMED), or a date/time (the date/time that a unit of blood is sent to the ward). An observation value is always represented as the data type specified in _OBX-2-value type_ of the same segment. Whether numeric or short text, the answer shall be recorded in ASCII text.

Reporting logically independent observations

The main sections of dictated reports, such as radiologic studies or history and physicals, are reported as separate OBX segments. In addition, each logically independent observation should be reported in a separate OBX segment, i.e., one OBX segment should not contain the *result* of more than one logically independent observation, unless it is part of a list of like concepts that belong together (e.g., a list of conditions tested for in newborn screening or mutations looked for in genomic testing). This requirement is included to assure that the contents of _OBX-6-units_, _OBX-8-interpretation codes_, and _OBX-9-probability_ can be interpreted unambiguously. This means that all other OBX field values apply equally to the whole of OBX-5 noting that OBX-6 does not apply in the case of coded values. The electrolytes and vital signs batteries, for example, would each be reported as four separate OBX segments. Two diagnostic impressions, e.g., congestive heart failure and pneumonia, would also be reported as two separate OBX segments whether reported as part of a discharge summary or chest X-ray report. Similarly, two bacterial organisms isolated in a single bacterial culture would be reported as two separate OBX segments.

Though two independent diagnostic *statements* cannot be reported in one OBX segment, unless they represent elements of a single list to which all other OBX field values apply equally, multiple categorical responses are allowed (usually as CWE data types separated by repeat delimiters), so long as they are fragments (modifiers) that together construct one diagnostic statement. Right upper lobe (recorded as one code) and pneumonia (recorded as another code), for example, could be both reported in one OBX segment. Such multiple "values" would be separated by repeat delimiters. The other example where use of repeat delimiters is allowed for coded values would be a list of conditions or mutations tested for to provide reference for the test results reported in related, but independent OBX segments. Multiple answers to a single question (for example mark all that apply type questions) could also be handled using this approach. It is important to state that ANY independent observation, that may require parent-child linking to additional tests, such as reflex testing, SHALL NOT be included in a single OBX-5 field using repeat delimiters, nor any list elements that require variations in the values of other OBX field values.

The following provides an example of how this may be communicated for 10 Cystic Fibrosis mutations, where the mutations are highlighted in red font (note that some labs test for as many as 140 mutations):

OBX|1|CWE|21656-4^CFTR gene mutations tested for in Blood or Tissue by Molecular genetics method Nominal ^LN|1|c.254G>A^^HGVS~c.350G>A^^HGVS~c.489+1G>T^^HGVS~c.579+1G>T^^HGVS~c.1000C>T^^HGVS~c.1040G>C^^HGVS~c.1364C>A^^HGVS~c.1519_1521del^^HGVS~c.1521_1523del^^HGVS~c.1585-1G>A^^HGVS|||N|||F

Multiple OBX segments with the same observation ID and Sub ID

In some systems, a single observation may include *fragments* of more than one data type. The most common example is a numeric result followed by coded comments (CWE). In this case, the logical observation can be sent in more than one OBX segment. For example, one segment of numeric data type for the numeric result and another segment of CWE data type for coded comments. If the producer was reporting multiple coded comments they would all be sent in one OBX segment separated by repeat delimiters because they all modified a single logical observation. Multiple OBX segments with the same observation ID and sub ID should always be sent in sequence with the most significant OBX segment (the one that has the normal flag/units and or reference range and status flag) first. The value of _OBX-6 through 12_ should be null in any following OBX segments with the same _OBX-3-observation identifier_ and _OBX-4-observation sub-ID_. For the purpose of replacement or deletion, multiple OBX segments with the same observation ID and sub ID are treated as a unit. If any are replaced or deleted, they all are replaced.

Coded values

When an OBX segment contains values of CWE data types, the observations are stored as a combination of codes and/or text. In Section _7.8.3_, "_CSS - Clinical Study Data Schedule Segment_," examples of results that are represented as CWE data types are shown in the first and second OBX segments of OBR 1 and the first and second OBX segments of OBR 2. The observation may be an observation battery ID (for recommended studies), a diagnostic code or finding (for a diagnostic impression), or an anatomic site for a pathology report, or any of the other kinds of coded results.

It is not necessary to always encode the information stored within a coded observation. For example, a chest X-ray impression could be transmitted as pure text even though it has a CWE data type. In this case, the test must be recorded as the second component of the *result code,* e.g.,

OBX|1|CWE|19005^X-Ray Impression^LN|1|^CONGESTIVE HEART FAILURE.|...<cr>

However, separate impressions, recommendations, etc., even if recorded as pure text, should be recorded in separate result segments. That is, congestive heart failure and pneumonia should not be sent as:

OBX|1|CWE|19005^X-Ray Impression^LN|1|^CONGESTIVE HEART FAILURE AND PNEUMONIA|...<cr>

but as:

OBX|1|CWE|19005^X-Ray Impression^LN|1|^CONGESTIVE HEART FAILURE|...<cr>

OBX|2|CWE|19005^X-Ray Impression^LN|2|^PNEUMONIA|....<cr>

Even better would be fully-coded results that include computer understandable codes (component 1) instead of, or in addition to, the text description (component 2). One may include multiple values in a CWE value and these can be mixtures of code and text, but only when they are needed to construct one diagnosis, impression, or concept. When text follows codes as an independent value it would be taken as a modifier or addenda to the codes. E.g.,

OBX|1|CWE|19005-8^X-ray impression^LN~29548-5^DiagnosisImpPatient^LN |1|428.0^CONGESTIVE HEART FAILURE^I9C~^MASSIVE HEART|...<cr>

The text in component 2 should be an accurate description of the code in component 1. Likewise, if used, the text in component 5 should be an accurate description of the code in component 4.

Insertion of CDA within an OBX:

CDA documents are to be exchanged in the OBX segment. The value of _OBX-2-Value Type_ should be set to 'ED'. _OBX-5-Observation Value_ contains the MIME package encoded as an encapsulated data type. The components should be valued as follows:

• Set the value of _OBX-5.2-Type of Data_ to 'multipart.'

• Set the value of _OBX-5.3-Data Subtype_ to '-hl7-cda-level-one.'

• Set the value of _OBX-5.4-Encoding_ to 'A'. (Note that a MIME package is not itself Base64-encoded. Rather entities within the MIME package are Base64-encoded. A MIME package is sent as ASCII text. Therefore, the correct value is 'A' not 'Base64.'

• Set the value of _OBX-5.5-Data_ to equal the MIME package. Every entity within the MIME package must be Base64-encoded. As stated in Chapter 2, "the data component must be scanned before transmission for HL7 delimiter characters (and other non-printing ASCII or non-ASCII characters such as LineFeed), and any found must be escaped by using the HL7 escape sequences defined in Section 2.7 'Use of escape sequences in text fields.' On the receiving application, the data field must be de-escaped after being parsed." As a result, CR/LF sequences required in the MIME package need to be escaped (i.e., converted to '\X0D0A\') prior to transmission. The content type of the first MIME entity is set to 'application/x-hl7-cda-level-one+xml', and should contain the CDA document itself. Multimedia objects referenced by the CDA document that need to be transmitted within the CDA document are to be placed in successive entities of the MIME package.

