==== 7.4.2.4 OBX-4 Observation Sub‑ID (OG) 00572

Components: <Original Sub-Identifier (ST)> ^ <Group (NM)> ^ <Sequence (NM)> ^ <Identifier (ST)>

Definition: This field is used to distinguish between multiple OBX segments with the same observation ID organized under one OBR. Starting with V2.8.2 the data type was changed from ST to OG to enable improved structured grouping of observation segments. In this enhanced mode, the first component provides backwards compatibility with existing grouping schemes, while the additional components can be used for improved structures as defined in specific conformance profiles. For example, a chest X-ray report might include three separate diagnostic impressions. The standard requires three OBX segments, one for each impression. By putting a 1 in the Sub-ID of the first of these OBX segments, 2 in the second, and 3 in the third, we can uniquely identify each OBX segment for editing or replacement.

The sub-identifier is also used to group related components in reports such as surgical pathology. It is traditional for surgical pathology reports to include all the tissues taken from one surgical procedure in one report. Consider, for example, a single surgical pathology report that describes the examination of gallbladder and appendix tissue. This report would be transmitted roughly as shown in Figure 7-2.

Figure 7-2. Example of sub-identifier usage – enhanced mode

OBR|1||1234^LAB|11529-5^Study report^LN|...<cr>

OBX|1|CWE|31208-2^Specimen source [Identifier] of Unspecified specimen^LN|^1^1^1|8231008^Gallbladder structure (body structure)^SCT|...<cr>

OBX|2|TX|22634-0^Path report.gross observation^LN|^1^2^1|THIS IS A NORMAL GALLBLADDER|...<cr>

OBX|3|TX|22635-7^Path report.microscopic observation^LN|^1^3^1|MICROSCOPIC EXAM SHOWS HISTOLOGICALLY NORMAL GALLBLADDER TISSUE|...<cr>

OBX|4|CWE|34574-4^Path report.final diagnosis^LN|^1^4^1|300355005^Gallbladder normal (finding)^SCT|...<cr>

OBX|5|CWE|31208-2^Specimen source [Identifier] of Unspecified specimen^LN|^2^1^1|66754008^Appendix structure (body structure)^SCT|...<cr>

OBX|6|TX|22634-0^Path report.gross observation^LN|^2^2^1|THIS IS A RED, INFLAMED, SWOLLEN, BOGGY APPENDIX|...<cr>

OBX|7|TX|22635-7^Path report.microscopic observation^LN|^2^3^1|INFILTRATION WITH MANY PMN's - INDICATING INFLAMATORY CHANGE|...<cr>

OBX|8|CWE|34574-4^Path report.final diagnosis^LN|^2^4^1|M-40000^INFLAMMATION NOS^SNM|...<cr>

The example in Figure 7-2 has two segments for each component of the report, one for each of the two tissues. Thus, there are two "31208-2^Specimen source [Identifier] of Unspecified specimen^LN" segments; there are two "22634-0^Path report.gross observation^LN" segments, and there are two "22635-7^Path report.microscopic observation^LN" segments. Segments that apply to the gallbladder all have the sub-identifier 1. Segments that apply to the appendix all have sub-identifier 2.

The observation sub ID has other grouping uses. It can be used to organize the reporting of some kinds of fluid intakes and outputs. For example, when intake occurs through multiple intravenous lines, a number of separate observations (OBX segments), the intake volume, the type of intake (Blood, D5W, Plasma, etc.), the site of the IV line, etc. may be needed for each intravenous line, each requiring a separate OBX segment. If more than one IV line is running, we can logically link all of the OBX segments that pertain to the first IV line by assigning them an observation sub ID of 1. We can do the same with the second IV line by assigning them a sub ID 2 and so on. The same would apply to the outputs of surgical drains when there are multiple such drains.

The use of the sub ID to distinguish repeating OBXs for the same observation ID is really a special case of using the sub ID to group, as can be seen if we picture the OBX segments in Figure 7-2 as part of a table where the rows correspond to a particular species of observation and the cells correspond to the sub ID numbers that would be associated with each corresponding OBX.

[width="100%",cols="28%,18%,18%,18%,18%",]
|===
|Distinct Observations |88304&ANT |22634-0^Path report.gross observation^LN |22635-7^Path report.microscopic observation^LN |34574-4^Path report.final diagnosis^LN
|Sub ID 1st Group |1 |1 |1 |1
|Sub ID 2nd Group |2 |2 |2 |2
|===

The use of Sub IDs to group results is equivalent to defining a table, and the use of sub IDs to distinguish repeats is just a special case, represented by one column in this table.

However, this approach introduces ambiguities if we have a set of repeating observations within a group, e.g., if the appendix observations include two impressions as in the 8th and 9th OBXs shown in Figure 7-3. This really represents the existence of a row nested within a single cell of the table given above.

Figure 7-3. Example of sub-identifier usage – original mode

OBX|1|CWE|880304&ANT|1|T57000^GALLBLADDER^SNM|...<cr>

OBX|2|TX|22634-0^Path report.gross observation^LN|1|THIS IS A NORMAL GALL BLADDER|...<cr>

OBX|3|TX|22635-7^Path report.microscopic observation^LN|1|MICROSCOPIC EXAMINATION SHOWS HISTOLOGICALLY

NORMAL GALLBLADDER TISSUE|...<cr>

OBX|4|CWE|34574-4^Path report.final diagnosis^LN|1|M-00100^NML^SNM|...<cr>

OBX|5|CWE|880304&ANT|2|T57000^APPENDIX^SNM|...<cr>

OBX|6|TX|22634-0^Path report.gross observation^LN|2|THIS IS A RED, INFLAMED APPENDIX|...<cr>

OBX|7|TX|22635-7^Path report.microscopic observation^LN|2|INFLAMMATION WITH MANY PUS CELLS-ACUTE INFLAMMATION|...<cr>

OBX|8|CWE|34574-4^Path report.final diagnosis^LN|2|M-40000^INFLAMMATION NOS^SNM|...<cr>

OBX|9|CWE|34574-4^Path report.final diagnosis^LN|2|M-30280^FECALITH^SNM|...<cr>

The text under _OBX-5-observation value_ provides guidance about dealing with two OBXs with the same observation ID and observation sub IDs. They are sent and replaced as a unit. However, some systems will take this to mean that the set of OBXs is to be combined into one composite observation in the receiving system. In original mode, this could use a dot and a string (similar to the Dewey Decimal system) notation that would be used when users wish to distinguish each of the repeats within one type, or results within a cell for editing and correction purposes. Using this system, Figure 7-3 would become 7-4. If there are cases where such nesting occurs at even deeper levels, this approach could be extended, although with the introduction of the OG data type we suggest the use of components 2-4 as described in Figure 7-2.

Figure 7-4. Example of sub-identifier usage – original mode with nesting

OBX|1|CWE||31208-2^Specimen source [Identifier] of Unspecified specimen^LN|1|28231008^Gallbladder structure (body structure)^SCT|...<cr>

OBX|2|TX|22634-0^Path report.gross observation^LN|1|THIS IS A NORMAL GALL BLADDER|...<cr>

OBX|3|TX|22635-7^Path report.microscopic observation^LN|1|MICROSCOPIC EXAMINATION SHOWS HISTOLOGICALLY

NORMAL GALLBLADDER TISSUE|...<cr>

OBX|4|CWE|34574-4^Path report.final diagnosis^LN|1|300355005^Gallbladder normal (finding)^SCT|...<cr>

OBX|5|CWE|31208-2^Specimen source [Identifier] of Unspecified specimen^LN|2|66754008^Appendix structure (body structure)^SCT|...<cr>

OBX|6|TX|22634-0^Path report.gross observation^LN|2|THIS IS A RED, INFLAMED APPENDIX|...<cr>

OBX|7|TX|22635-7^Path report.microscopic observation^LN|2|INFLAMMATION WITH MANY PUS CELLS-ACUTE INFLAMMATION|...<cr>

OBX|8|CWE|34574-4^Path report.final diagnosis^LN|2.1|M-40000^INFLAMMATION NOS^SNM|...<cr>

OBX|9|CWE|34574-4^Path report.final diagnosis^LN|2.2|M-30280^FECALITH^SNM|...<cr>

Use a null or 1 when there is no need for multiples.

If the observation includes a number of OBXs with the same value for the observation ID OBX-3, then one must use different values for the sub-ID. If there is no need to group or sequence any further, the original mode can continue to be used to ensure uniqueness of OBX as shown in the example below of an electrocardiograph chest radiograph report with three diagnostic impressions, using 1,2,3 in the sub-ID field to distinguish the three separate results.

Figure 7-5. Example of Sub-ID used to distinguish three independent results with the same observation ID – without grouping/sequencing

OBX|1|CWE|8601-7^EKG IMPRESSION ^LN|1|^atrial fibrillation|...<cr>

OBX|2|CWE|8601-7^EKG IMPRESSION ^LN|2|^OLD SEPTAL MYOCARDIAL INFARCT|...<cr>

OBX|3|CWE|8601-7^EKG IMPRESSION ^LN|3|^poor R wave progression|...<cr>

