==== 7.4.2.2 OBX-2 Value Type (ID) 00570

____
Definition: This field defines the data type of OBX-5, Observation Value. If OBX-5, Observation Value, is valued then OBX-2, Value Type, SHALL be valued. When OBX-5, Observation Value, is not valued, OBX-2 Value Type MAY be valued to represent a data type used to value the observation expressed in OBX-3, Observation Identifier. See https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmcmail.mayo.edu%2Fowa%2FUrlBlockedError.aspx&data=02%7C01%7CHans.Buitendijk%40Cerner.com%7C94563515a95347b47e2a08d56ca7de79%7C0ffca1dc22de4c19b786f0dbf79a3c2e%7C0%7C0%7C636534390612534684&sdata=98cL%2B7xxtWw9ruy81%2FrxSZUwPIHr2uRIsEX2zsmJT%2BI%3D&reserved=0[_HL7 Table 0125 – Value Types_] for valid values.

Condition: This field is required if OBX-5, Observation Value, is valued.
____

For example, if the value is 'CWE' then the result in OBX-5 must be a coded entry or text or both. As of v 2.7, the ST data type may not be used to transmit data that can be more precisely transmitted using other data types, e.g. SN when comparative symbols are needed.

The RP value (reference pointer) must be used if the OBX-5 contains a pointer to the data e.g., a URL of an image. The receiving system can use this reference pointer whenever it needs access to the actual data through other interface standards, e.g., DICOM, or through appropriate data base servers.

The structured numeric (SN) data type provides for reporting ranges (e.g., 3-5 or 10-20), titres (e.g., 1:10), and out-of-range indicators (e.g., >50) in a structured and computer-interpretable way.

We allow the FT data type in the OBX segment, but its use is discouraged. Formatted text usually implies a meaningful structure, e.g., a list of three independent diagnoses reported on different lines. But ideally, the structure in three independent diagnostic statements would be reported as three separate OBX segments.

TX should *not* be used except to send large amounts of text. In the TX data type, the repeat delimiter can only be used to identify paragraph breaks. Use ST to send short, and possibly encodable, text strings.

CDA documents are to be exchanged in the OBX segment in any message that can exchange documents (such as MDM or ORU). Within the OBX segment, the MIME package is encoded as an encapsulated (ED) data type.

