==== 5.5.1.4 DSP-4 Logical Break Point (ST) 00064 

Definition: This field is non‑null if this line is the last line of a logical break point in the response as defined by the responding system.

Often the lines of display text will fall into logical groups that differ from the physical size of a screen or printer page. For example, a complete battery or an entire radiology report might be thought of as comprising a logical group, though it might have as few as six or as many as 120 lines. Knowledge of the logical break points in the display data can be useful to the application system that is displaying or printing data. For this reason, _DSP-4-Logical break point_ is used. The sending application (the one that formats the data) places the logical break points where appropriate. If there is a particular ancillary result ID associated with the data delineated by _DSP-4-Logical break point_, the value of this ID also can be returned in _DSP-5-Result ID_. Then if the user selects the area of the display delineated by _DSP-4-Logical break point_, the displaying system can query for the associated _DSP-5-Result ID_.

