==== 5.6.1.2 Deferred response example

The Client submits the following query and indicates that a deferred response is desired by setting _RCP-1-Response priority_ to "D".

MSH|^~\&|PCR|Gen Hosp|PIMS||199811201400-0800||QBP^Q42^QBP_Q13|ACK9901|P|2.8||||||||

QPD|Q42^Tabular Dispense History^HL7nnn|Q0010|555444222111^^^MPI^MR| |19980531|19990531|

RCP|D|999^RD|

RDF|3|PatientList^ST^20~PatientName^XPN^48~MedicationDispensed^ST^40~RXD.3^DTM^24

The Server responds one minute later with a general acknowledgement.

MSH|^~\&|PIMS|Gen Hosp|PCR||199811201401-0800||ACK^Q42^ACK|8875|P|2.8||||||||

MSA|AA|8699|

The Server responds the following morning with the desired data.

MSH|^~\&|PIMS|Gen Hosp|PCR||199811210300-0800||RTB^K42^RTB_K13|9950|P|2.8||||||||

QAK|Q010|OK|Q42^Tabular Dispense History^HL7nnn|4

QPD|Q42^Tabular Dispense History^HL7nnn|Q0010|555444222111^^^MPI^MR||19980531|19990531|

RDF|7|PatientId^CX^20~PatientName^XPN^48~OrderControlCode^ID^2~ MedicationDispensed^CWE^100~DispenseDate^DTM^24~QuantityDispensed^NM^20~ OrderingProvider^XCN^120

RDT|555444222111^^^MPI^MR|Everyman^Adam|RE|525440345^Verapamil Hydrochloride 120 mg TAB^NDC |199805291115-0700|100|77^Hippocrates^Harold^H^III^DR^MD

RDT|555444222111^^^MPI^MR|Everyman^Adam|RE|00182196901^VERAPAMIL HCL ER TAB 180MG ER^NDC |19980821-0700|100|77^Hippocrates^Harold^H^III^DR^MD

RDT|555444222111^^^MPI^MR|Everyman^Adam|RE|00172409660^BACLOFEN 10MG TABS^NDC |199809221415-0700|10|88^Seven^Henry^^^DR^MD

RDT|555444222111^^^MPI^MR|Everyman^Adam|RE|00054384163^THEOPHYLLINE 80MG/15ML SOLN^NDC|199810121145-0700|10|99^Assigned^Amanda^^^DR^MD

The Client responds immediately with a general acknowledgement.

MSH|^~\&|PCR|Gen Hosp|PIMS||199811210300-0800||ACK^K42^ACK|8750|P|2.8||||||||

MSA|AA|9950|

